it("PayBills_VerifyMakeOneTimePayment", async function() {
	kony.automation.textbox.enterText(["frmLogin","tbxUsername"],"uatuser20");
	kony.automation.textbox.enterText(["frmLogin","tbxPassword"],"Kony@1234");
	kony.automation.button.click(["frmLogin","btnLogIn"]);
	await kony.automation.playback.waitFor(["frmFullScreenAds","flxCancel"]);
	kony.automation.flexcontainer.click(["frmFullScreenAds","flxCancel"]);
	await kony.automation.playback.waitFor(["frmDashboardAggregated","customHeader","flxBack"]);
	kony.automation.flexcontainer.click(["frmDashboardAggregated","customHeader","flxBack"]);
	await kony.automation.playback.waitFor(["frmDashboardAggregated","Hamburger","segHamburger"]);
	kony.automation.segmentedui.click(["frmDashboardAggregated","Hamburger","segHamburger[0,4]"]);
	await kony.automation.playback.waitFor(["frmBillPay","flxPayABill"]);
	kony.automation.flexcontainer.click(["frmBillPay","flxPayABill"]);
	await kony.automation.playback.waitFor(["frmBillPaySelectPayee","segAccounts"]);
	kony.automation.segmentedui.click(["frmBillPaySelectPayee","segAccounts[0,0]"]);
	await kony.automation.playback.waitFor(["frmBillPayAmount","keypad","btnOne"]);
	kony.automation.button.click(["frmBillPayAmount","keypad","btnOne"]);
	kony.automation.button.click(["frmBillPayAmount","keypad","btnFive"]);
	kony.automation.button.click(["frmBillPayAmount","keypad","btnZero"]);
	kony.automation.button.click(["frmBillPayAmount","btnContinue"]);
	await kony.automation.playback.waitFor(["frmBillPayFrequency","segFrequency"]);
	kony.automation.segmentedui.click(["frmBillPayFrequency","segFrequency[0,1]"]);
	await kony.automation.playback.waitFor(["frmBillPayStartDate","customCalendar","flxNextMonth"]);
	kony.automation.flexcontainer.click(["frmBillPayStartDate","customCalendar","flxNextMonth"]);
	await kony.automation.playback.waitFor(["frmBillPayStartDate","customCalendar","flxMonth"]);
	kony.automation.widget.touch(["frmBillPayStartDate","customCalendar","flxMonth"], [83,159],null,[83,159]);
	await kony.automation.playback.waitFor(["frmBillPayStartDate","customCalendar","m3CopyLabel0cf3274f2e04840"]);
	kony.automation.widget.touch(["frmBillPayStartDate","customCalendar","m3CopyLabel0cf3274f2e04840"], [15,15],null,[15,15]);
	await kony.automation.playback.waitFor(["frmBillPayStartDate","btnContinue"]);
	kony.automation.button.click(["frmBillPayStartDate","btnContinue"]);
	kony.automation.textbox.enterText(["frmBillPayConfirmation","txtDescription"],"Notes170520003644");
	await kony.automation.playback.waitFor(["frmBillPayConfirmation","flxCheckBox"]);
	kony.automation.flexcontainer.click(["frmBillPayConfirmation","flxCheckBox"]);
	await kony.automation.playback.waitFor(["frmBillPayConfirmation","btnContinue"]);
	kony.automation.button.click(["frmBillPayConfirmation","btnContinue"]);
	await kony.automation.playback.waitFor(["frmBillPay","customHeader","flxBack"]);
	kony.automation.flexcontainer.click(["frmBillPay","customHeader","flxBack"]);
	await kony.automation.playback.waitFor(["frmBillPay","Hamburger","flxLogout"]);
	kony.automation.widget.touch(["frmBillPay","Hamburger","flxLogout"], [33,17],[[33,17],[33,17],[33,16],[33,16]],[33,16]);
	await kony.automation.playback.waitFor(["frmLogout","btnLogIn"]);
	kony.automation.button.click(["frmLogout","btnLogIn"]);
});