define(function() {
    return {
        "properties": [{
            "name": "sknHeaderLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successTransactionIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "notesLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "failureTransactionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknHeaderBackground",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "failureTransactionIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "notesValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "failureTransactionDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transactionStatus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRowSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "supportingDocumentsLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "failureButtonAction1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backButtonIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeStatus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFieldLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "supportingDocumentsValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "currencyCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pngImage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFieldValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addressLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "jpegImage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransactionSuccessLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addressLine1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransactionFailureTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addressLine2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransactionFailureDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "mobileLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "mobileValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "emailLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "emailValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cityValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "stateValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "postalCodeValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field11Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field11Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field12Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field12Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field13Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field13Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field14Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field14Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field15Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field15Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field16Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field16Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field17Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field17Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field18Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field18Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field19Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field19Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field20Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field20Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field21Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field21Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field22Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field22Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field23Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field23Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field24Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field24Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successButtonAction1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successButtonAction2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successButtonAction3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successButtonAction4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successTransactionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": ["setContext", "onError", "getBtnEntitlement", "contextualActionButtonOnClick", "onBack"]
    }
});