define(function() {
    return {
        "properties": [{
            "name": "buttonDisabledSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordPolicyService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textVisiblityOffIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "otpRequestLimitError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "buttonEnabledSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "object",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textVisiblityOnIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblOTPEmpty",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "requestResetPasswordOTP",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tickGrayIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblOTPNotEmpty",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyMFAOTP",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tickGreenIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFlxOTPEmpty",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordUpdateService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFlxOTPNotEmpty",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFlxNormalSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["resetUI", "navigateToMFA"],
        "events": ["onSuccessCallback", "onFailureCallback", "cancelReset"]
    }
});