define(function() {
    return {
        "properties": [{
            "name": "startDate",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "thirdRowName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "activeTabVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "firstRowName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "startDateValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "activeTabName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "firstRowVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "thirdRowValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "secondRowVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "firstRowValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "thirdRowVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "labelNameSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "frequencyView",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "labelValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "activeTabSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setFirstRowNamei18", "setFirstRowName", "setFirstRowValue", "setSecondRowNamei18", "setSecondRowName", "setSecondRowValue", "setThirdRowNamei18", "setThirdRowName", "setThirdRowValue", "setActiveTabValue"],
        "events": ["onHandleAction"]
    }
});