define(function() {
    return {
        "properties": [{
            "name": "iconVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "moreLink",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "BREAKPTS",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "boxSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "icon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "moreLinkAction",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "title",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionButton1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "descriptionSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "description",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionButton2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "moreLinkSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "descriptionRendering",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "detailsActionButton1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionButton1Skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "teamsConditions",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "detailsActionButton2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionButton2Skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "detailsActionButton1Skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "detailsActionButton2Skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "detailDescriptionSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "detailDescHeadingSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "popupTitleSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "popupDescriptionSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "termsConditionTitleSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "termsConditionSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "popupCloseBtnSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["closeDescription"],
        "events": ["transferTypeDetails", "buttonActionHandling", "enableHideDescription", "setContext"]
    }
});