define(function() {
    return {
        "properties": [{
            "name": "imgSearchIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billerSearchObjectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "isSearchEnabled",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblField1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tbxSearch",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billerSearchObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "isManualAdditionEnabled",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblFocusSkin1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billerSearchOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblField2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "navigateToForm",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billerSearchCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblFocusSkin2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "navigateFromCountryCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnSearchClear",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billerSearchIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblField3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "navigateToManualFlow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "imgLabelFieldIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblFocusSkin3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchResultIntoContext",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "skntbxSearchInput",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "skntbxSearch",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknBtnSearchClear",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext", "clearContext"],
        "events": []
    }
});