define(function() {
    return {
        "properties": [{
            "name": "lblField1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btn1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maxDataEntries",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeObjectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionButtonFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dvfConfig",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btn1Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTextValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "minFillMapping",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeEDITOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTextValueFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeEDITCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblErrorPrompt",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeEDITIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField6",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTextBoxError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtValue1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionButtonBlocked",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtValue2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblErrorPrompt",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtValue3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtValue4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtValue5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtValue6",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": ["setContext"]
    }
});