/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"userDetails": "userDetails",
		"firstName": "firstName",
		"lastName": "lastName",
		"middleName": "middleName",
		"phoneNumber": "phoneNumber",
		"phoneCountryCode": "phoneCountryCode",
		"ssn": "ssn",
		"dob": "dob",
		"drivingLicenseNumber": "drivingLicenseNumber",
		"coreCustomerId": "coreCustomerId",
		"email": "email",
		"isEnrolled": "isEnrolled",
		"companyList": "companyList",
		"companyName": "companyName",
		"contractId": "contractId",
		"contractName": "contractName",
		"cif": "cif",
		"isPrimary": "isPrimary",
		"serviceDefinition": "serviceDefinition",
		"userRole": "userRole",
		"accounts": "accounts",
		"accountName": "accountName",
		"accountId": "accountId",
		"isEnabled": "isEnabled",
		"accountType": "accountType",
		"accountLevelPermissions": "accountLevelPermissions",
		"permissionType": "permissionType",
		"featurePermissions": "featurePermissions",
		"featureId": "featureId",
		"featureDescription": "featureDescription",
		"featureName": "featureName",
		"id": "id",
		"globalLevelPermissions": "globalLevelPermissions",
		"permissions": "permissions",
		"transactionLimits": "transactionLimits",
		"individualTransaction": "individualTransaction",
		"limitType": "limitType",
		"limit": "limit",
		"bulkTransactionLimits": "bulkTransactionLimits",
		"actionId": "actionId",
		"actionDescription": "actionDescription",
		"actionName": "actionName",
		"customers": "customers",
		"name": "name",
		"isAlreadyAssociatedwithContract": "isAlreadyAssociatedwithContract",
		"dbpErrCode": "dbpErrCode",
		"dbpErrMsg": "dbpErrMsg",
		"dateOfBirth": "dateOfBirth",
		"status": "status",
		"value": "value",
		"limits": "limits",
		"roleId": "roleId",
		"userId": "userId",
		"customRoleName": "customRoleName",
		"isDuplicate": "isDuplicate",
		"customRoles": "customRoles",
		"customRoleDetails": "customRoleDetails",
		"users": "users",
		"contractDetails": "contractDetails",
		"companies": "companies",
		"coreCustomerName": "coreCustomerName",
		"infinityUserId": "infinityUserId",
		"limitGroupId": "limitGroupId",
		"customerId": "customerId",
		"removedCompanies": "removedCompanies",
		"userList": "userList",
		"userName": "userName",
		"isEditPermissionEnabled": "isEditPermissionEnabled",
		"isCreatePermissionEnabled": "isCreatePermissionEnabled",
		"isViewPermissionEnabled": "isViewPermissionEnabled",
		"serviceDefinitionName": "serviceDefinitionName",
		"limitGroupName": "limitGroupName",
		"limitGroupDescription": "limitGroupDescription",
		"password": "password",
		"fistName": "fistName",
		"isNotificationRequired": "isNotificationRequired",
		"partyId": "partyId",
		"companyId": "companyId",
		"isProfileExist": "isProfileExist",
		"createdby": "createdby",
		"createdts": "createdts",
		"isOnBoradingFlow": "isOnBoradingFlow",
		"applicationId": "applicationId",
	};

	Object.freeze(mappings);

	var typings = {
		"userDetails": "string",
		"firstName": "string",
		"lastName": "string",
		"middleName": "string",
		"phoneNumber": "string",
		"phoneCountryCode": "string",
		"ssn": "string",
		"dob": "string",
		"drivingLicenseNumber": "string",
		"coreCustomerId": "string",
		"email": "string",
		"isEnrolled": "string",
		"companyList": "string",
		"companyName": "string",
		"contractId": "string",
		"contractName": "string",
		"cif": "string",
		"isPrimary": "string",
		"serviceDefinition": "string",
		"userRole": "string",
		"accounts": "string",
		"accountName": "string",
		"accountId": "string",
		"isEnabled": "string",
		"accountType": "string",
		"accountLevelPermissions": "string",
		"permissionType": "string",
		"featurePermissions": "string",
		"featureId": "string",
		"featureDescription": "string",
		"featureName": "string",
		"id": "string",
		"globalLevelPermissions": "string",
		"permissions": "string",
		"transactionLimits": "string",
		"individualTransaction": "string",
		"limitType": "string",
		"limit": "string",
		"bulkTransactionLimits": "string",
		"actionId": "string",
		"actionDescription": "string",
		"actionName": "string",
		"customers": "string",
		"name": "string",
		"isAlreadyAssociatedwithContract": "string",
		"dbpErrCode": "string",
		"dbpErrMsg": "string",
		"dateOfBirth": "string",
		"status": "string",
		"value": "string",
		"limits": "string",
		"roleId": "string",
		"userId": "string",
		"customRoleName": "string",
		"isDuplicate": "string",
		"customRoles": "string",
		"customRoleDetails": "string",
		"users": "string",
		"contractDetails": "string",
		"companies": "string",
		"coreCustomerName": "string",
		"infinityUserId": "string",
		"limitGroupId": "string",
		"customerId": "string",
		"removedCompanies": "string",
		"userList": "string",
		"userName": "string",
		"isEditPermissionEnabled": "string",
		"isCreatePermissionEnabled": "string",
		"isViewPermissionEnabled": "string",
		"serviceDefinitionName": "string",
		"limitGroupName": "string",
		"limitGroupDescription": "string",
		"password": "string",
		"fistName": "string",
		"isNotificationRequired": "string",
		"partyId": "string",
		"companyId": "string",
		"isProfileExist": "string",
		"createdby": "string",
		"createdts": "string",
		"isOnBoradingFlow": "string",
		"applicationId": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"id",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "RBObjects",
		tableName: "InfinityUser"
	};

	Object.freeze(config);

	return config;
})