define(function() {
    return {
        "properties": [{
            "name": "totalTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "totalNumberSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "legendSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "criteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext"],
        "events": ["onError", "requestStart", "requestEnd"]
    }
});