it("WireTransfer_AddInternationalAccount", async function() {
	kony.automation.textbox.enterText(["frmLogin","tbxUsername"],"dbxJasmine1234");
	kony.automation.textbox.enterText(["frmLogin","tbxPassword"],"Kony@1234");
	kony.automation.button.click(["frmLogin","btnLogIn"]);
	await kony.automation.playback.waitFor(["frmFullScreenAds","flxCancel"]);
	kony.automation.flexcontainer.click(["frmFullScreenAds","flxCancel"]);
	await kony.automation.playback.waitFor(["frmDashboardAggregated","customHeader","flxBack"]);
	kony.automation.flexcontainer.click(["frmDashboardAggregated","customHeader","flxBack"]);
	await kony.automation.playback.waitFor(["frmDashboardAggregated","Hamburger","segHamburger"]);
	kony.automation.segmentedui.click(["frmDashboardAggregated","Hamburger","segHamburger[0,3]"]);
	await kony.automation.playback.waitFor(["frmManageRecipientType","segRecipientType"]);
	kony.automation.segmentedui.click(["frmManageRecipientType","segRecipientType[0,2]"]);
	await kony.automation.playback.waitFor(["frmManageRecipientList","btnAddRecipient"]);
	kony.automation.button.click(["frmManageRecipientList","btnAddRecipient"]);
	await kony.automation.playback.waitFor(["frmBenSwiftCode","txtSwiftCode"]);
	kony.automation.textbox.enterText(["frmBenSwiftCode","txtSwiftCode"],"BNCRCRSJ");
	await kony.automation.playback.waitFor(["frmBenSwiftCode","btnContinue"]);
	kony.automation.button.click(["frmBenSwiftCode","btnContinue"]);
	await kony.automation.playback.waitFor(["frmEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnTwo"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnThree"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFour"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnSix"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnSeven"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnEight"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnNine"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnZero"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnTwo"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnThree"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFour"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnSix"]);
	kony.automation.button.click(["frmEnterBenAccNo","btnContinue"]);
	await kony.automation.playback.waitFor(["frmReEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnTwo"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnThree"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFour"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnSix"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnSeven"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnEight"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnNine"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnZero"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnTwo"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnThree"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFour"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnSix"]);
	kony.automation.button.click(["frmReEnterBenAccNo","btnContinue"]);
	await kony.automation.playback.waitFor(["frmBenName","txtRecipientName"]);
	kony.automation.textbox.enterText(["frmBenName","txtRecipientName"],"National Bank");
	kony.automation.button.click(["frmBenName","btnContinue"]);
	await kony.automation.playback.waitFor(["frmBenVerifyDetails","btnContinue"]);
	kony.automation.button.click(["frmBenVerifyDetails","btnContinue"]);
	await kony.automation.playback.waitFor(["frmManageRecipientList","tbxSearch"]);
	kony.automation.widget.touch(["frmManageRecipientList","tbxSearch"], [160,17],null,[160,33]);
	await kony.automation.playback.waitFor(["frmManageRecipientList","customSearchbox","tbxSearch"]);
	kony.automation.textbox.enterText(["frmManageRecipientList","customSearchbox","tbxSearch"],"National Bank");
	await kony.automation.playback.waitFor(["frmManageRecipientList","segRecipients"]);
	kony.automation.widget.touch(["frmManageRecipientList","segRecipients[0,0]","flxAccountsNoImage"], [67,21],null,[67,21]);
	await kony.automation.playback.waitFor(["frmManageTransferRecipientInfo","btnDeleteRecipient"]);
	kony.automation.button.click(["frmManageTransferRecipientInfo","btnDeleteRecipient"]);
	kony.automation.alert.click(0);
	await kony.automation.playback.waitFor(["frmManageRecipientList","customHeader","flxBack"]);
	kony.automation.flexcontainer.click(["frmManageRecipientList","customHeader","flxBack"]);
	await kony.automation.playback.waitFor(["frmManageRecipientType","customHeader","flxBack"]);
	kony.automation.flexcontainer.click(["frmManageRecipientType","customHeader","flxBack"]);
	kony.automation.flexcontainer.click(["frmDashboardAggregated","customHeader","flxBack"]);
	await kony.automation.playback.waitFor(["frmDashboardAggregated","Hamburger","flxLogout"]);
	kony.automation.widget.touch(["frmDashboardAggregated","Hamburger","flxLogout"], [27,39],null,[27,39]);
	await kony.automation.playback.waitFor(["frmLogout","btnLogIn"]);
	kony.automation.button.click(["frmLogout","btnLogIn"]);
});