it("WireTransfer_TransferToAddedRecipient", async function() {
	kony.automation.textbox.enterText(["frmLogin","tbxUsername"],"dbxJasmine1234");
	kony.automation.textbox.enterText(["frmLogin","tbxPassword"],"Kony@1234");
	kony.automation.button.click(["frmLogin","btnLogIn"]);
	await kony.automation.playback.waitFor(["frmFullScreenAds","flxCancel"]);
	kony.automation.flexcontainer.click(["frmFullScreenAds","flxCancel"]);
	await kony.automation.playback.waitFor(["frmDashboardAggregated","customHeader","flxBack"]);
	kony.automation.flexcontainer.click(["frmDashboardAggregated","customHeader","flxBack"]);
	await kony.automation.playback.waitFor(["frmDashboardAggregated","Hamburger","segHamburger"]);
	kony.automation.segmentedui.click(["frmDashboardAggregated","Hamburger","segHamburger[0,3]"]);
	kony.automation.segmentedui.click(["frmManageRecipientType","segRecipientType[0,0]"]);
	await kony.automation.playback.waitFor(["frmManageRecipientList","btnAddRecipient"]);
	kony.automation.button.click(["frmManageRecipientList","btnAddRecipient"]);
	await kony.automation.playback.waitFor(["frmEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnTwo"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnThree"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFour"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnSix"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnSeven"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnEight"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnNine"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnZero"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnTwo"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnThree"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFour"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnSix"]);
	kony.automation.button.click(["frmEnterBenAccNo","btnContinue"]);
	await kony.automation.playback.waitFor(["frmReEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnTwo"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnThree"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFour"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnSix"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnSeven"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnEight"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnNine"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnZero"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnOne"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnTwo"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnThree"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFour"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnSix"]);
	kony.automation.button.click(["frmReEnterBenAccNo","btnContinue"]);
	await kony.automation.playback.waitFor(["frmBenName","txtRecipientName"]);
	kony.automation.textbox.enterText(["frmBenName","txtRecipientName"],"Test recipient");
	await kony.automation.playback.waitFor(["frmBenName","btnContinue"]);
	kony.automation.button.click(["frmBenName","btnContinue"]);
	await kony.automation.playback.waitFor(["frmBenVerifyDetails","btnContinue"]);
	kony.automation.button.click(["frmBenVerifyDetails","btnContinue"]);
	await kony.automation.playback.waitFor(["frmManageRecipientList","tbxSearch"]);
	kony.automation.widget.touch(["frmManageRecipientList","tbxSearch"], [51,16],null,[71,43]);
	await kony.automation.playback.waitFor(["frmManageRecipientList","customSearchbox","tbxSearch"]);
	kony.automation.textbox.enterText(["frmManageRecipientList","customSearchbox","tbxSearch"],"Test recipient");
	await kony.automation.playback.waitFor(["frmManageRecipientList","segRecipients"]);
	kony.automation.segmentedui.click(["frmManageRecipientList","segRecipients[0,0]"]);
	await kony.automation.playback.waitFor(["frmManageTransferRecipient","btnTransfer"]);
	kony.automation.button.click(["frmManageTransferRecipient","btnTransfer"]);
	await kony.automation.playback.waitFor(["frmMMTransferFromAccount","tbxSearch"]);
	kony.automation.widget.touch(["frmMMTransferFromAccount","tbxSearch"], [160,17],null,[160,61]);
	await kony.automation.playback.waitFor(["frmMMTransferFromAccount","customSearchbox","tbxSearch"]);
	kony.automation.textbox.enterText(["frmMMTransferFromAccount","customSearchbox","tbxSearch"],"My Checking");
	await kony.automation.playback.waitFor(["frmMMTransferFromAccount","segTransactions"]);
	kony.automation.segmentedui.click(["frmMMTransferFromAccount","segTransactions[0,0]"]);
	await kony.automation.playback.waitFor(["frmMMTransferAmount","keypad","btnOne"]);
	kony.automation.button.click(["frmMMTransferAmount","keypad","btnOne"]);
	kony.automation.button.click(["frmMMTransferAmount","keypad","btnZero"]);
	kony.automation.button.click(["frmMMTransferAmount","keypad","btnZero"]);
	kony.automation.button.click(["frmMMTransferAmount","btnContinue"]);
	await kony.automation.playback.waitFor(["frmMMReview","txtDescription"]);
	kony.automation.textarea.enterText(["frmMMReview","txtDescription"],"notes");
	kony.automation.button.click(["frmMMReview","btnTransfer"]);
});