it("Verify_Someone_Else_Flow_Email", async function() {
	kony.automation.textbox.enterText(["frmLogin","tbxUsername"],"dbxJasmine1234");
	kony.automation.textbox.enterText(["frmLogin","tbxPassword"],"Kony@1234");
	kony.automation.button.click(["frmLogin","btnLogIn"]);
	await kony.automation.playback.waitFor(["frmDashboardAggregated","customHeader","flxBack"]);
	await kony.automation.playback.wait(1000);
	kony.automation.flexcontainer.click(["frmDashboardAggregated","customHeader","flxBack"]);
	kony.automation.segmentedui.click(["frmDashboardAggregated","Hamburger","segHamburger[0,7]"]);
	await kony.automation.playback.wait(1000);
	kony.automation.flexcontainer.click(["frmCardLessHome","flxWithdrawCash"]);
	await kony.automation.playback.wait(1000);
	kony.automation.button.click(["frmCardLessCashRec","btnSomeoneCollect"]);
	await kony.automation.playback.wait(1000);
	kony.automation.button.click(["frmCardLessContactType","btnEmail"]);
	await kony.automation.playback.wait(1000);
	kony.automation.textbox.enterText(["frmCardLessEmail","txtEmailId"],"abc@temenos.com");
	kony.automation.button.click(["frmCardLessEmail","btnContinue"]);
	kony.automation.textbox.enterText(["frmCardLessRecName","txtFirstName"],"Test");
	kony.automation.textbox.enterText(["frmCardLessRecName","txtLastName"],"1");
	kony.automation.button.click(["frmCardLessRecName","btnContinue"]);
	await kony.automation.playback.wait(1000);
	kony.automation.button.click(["frmCardLessWithdraw","keypad","btnFive"]);
	kony.automation.button.click(["frmCardLessWithdraw","keypad","btnZero"]);
	kony.automation.button.click(["frmCardLessWithdraw","keypad","btnZero"]);
	kony.automation.button.click(["frmCardLessWithdraw","keypad","btnZero"]);
	kony.automation.button.click(["frmCardLessWithdraw","btnContinue"]);
	await kony.automation.playback.wait(1000);
	kony.automation.textbox.enterText(["frmCardLessSecureCode","txtSecureCode"],"1234");
	kony.automation.textbox.enterText(["frmCardLessSecureCode","txtReenterCode"],"1234");
	kony.automation.button.click(["frmCardLessSecureCode","btnContinue"]);
	await kony.automation.playback.wait(1000);
	kony.automation.button.click(["frmCardLessConfWithdraw","btnConfirm"]);
	await kony.automation.playback.wait(1000);
	kony.automation.button.click(["frmCardLessCWCode","btnDone"]);
	await kony.automation.playback.wait(1000);
	kony.automation.flexcontainer.click(["frmCardLessHome","customHeader","flxBack"]);
	kony.automation.widget.touch(["frmCardLessHome","Hamburger","flxLogout"], null,null,[34,29]);
});