it("Verify_Someone_Else_Flow_Phone", async function() {
	kony.automation.textbox.enterText(["frmLogin","tbxUsername"],"dbxJasmine1234");
	kony.automation.textbox.enterText(["frmLogin","tbxPassword"],"Kony@1234");
	kony.automation.button.click(["frmLogin","btnLogIn"]);
	await kony.automation.playback.waitFor(["frmDashboardAggregated","customHeader","flxBack"]);
	await kony.automation.playback.wait(1000);
	kony.automation.flexcontainer.click(["frmDashboardAggregated","customHeader","flxBack"]);
	kony.automation.segmentedui.click(["frmDashboardAggregated","Hamburger","segHamburger[0,7]"]);
	await kony.automation.playback.wait(2000);
	kony.automation.flexcontainer.click(["frmCardLessHome","flxWithdrawCash"]);
	kony.automation.button.click(["frmCardLessCashRec","btnSomeoneCollect"]);
	kony.automation.button.click(["frmCardLessContactType","btnPhoneNumber"]);
	kony.automation.button.click(["frmCardLessPhoneNo","keypad","btnEight"]);
	kony.automation.button.click(["frmCardLessPhoneNo","keypad","btnNine"]);
	kony.automation.button.click(["frmCardLessPhoneNo","keypad","btnSix"]);
	kony.automation.button.click(["frmCardLessPhoneNo","keypad","btnThree"]);
	kony.automation.button.click(["frmCardLessPhoneNo","keypad","btnFour"]);
	kony.automation.button.click(["frmCardLessPhoneNo","keypad","btnOne"]);
	kony.automation.button.click(["frmCardLessPhoneNo","keypad","btnSix"]);
	kony.automation.button.click(["frmCardLessPhoneNo","keypad","btnOne"]);
	kony.automation.button.click(["frmCardLessPhoneNo","keypad","btnTwo"]);
	kony.automation.button.click(["frmCardLessPhoneNo","keypad","btnOne"]);
	kony.automation.button.click(["frmCardLessPhoneNo","btnContinue"]);
	kony.automation.textbox.enterText(["frmCardLessRecName","txtFirstName"],"Test");
	kony.automation.textbox.enterText(["frmCardLessRecName","txtLastName"],"User");
	kony.automation.button.click(["frmCardLessRecName","btnContinue"]);
	await kony.automation.playback.wait(2000);
	kony.automation.button.click(["frmCardLessWithdraw","keypad","btnFive"]);
	kony.automation.button.click(["frmCardLessWithdraw","keypad","btnZero"]);
	kony.automation.button.click(["frmCardLessWithdraw","keypad","btnZero"]);
	kony.automation.button.click(["frmCardLessWithdraw","keypad","btnZero"]);
	kony.automation.button.click(["frmCardLessWithdraw","btnContinue"]);
	kony.automation.textbox.enterText(["frmCardLessSecureCode","txtSecureCode"],"1234");
	kony.automation.textbox.enterText(["frmCardLessSecureCode","txtReenterCode"],"1233");
	kony.automation.button.click(["frmCardLessSecureCode","btnContinue"]);
	kony.automation.textbox.enterText(["frmCardLessSecureCode","txtReenterCode"],"1234");
	kony.automation.button.click(["frmCardLessSecureCode","btnContinue"]);
	kony.automation.textarea.enterText(["frmCardLessConfWithdraw","txtDescription"],"expense");
	kony.automation.button.click(["frmCardLessConfWithdraw","btnConfirm"]);
	await kony.automation.playback.wait(2000);
	kony.automation.button.click(["frmCardLessCWCode","btnDone"]);
	await kony.automation.playback.wait(2000);
	kony.automation.flexcontainer.click(["frmCardLessHome","customHeader","flxBack"]);
	await kony.automation.playback.wait(1000);
	kony.automation.widget.touch(["frmCardLessHome","Hamburger","flxLogout"], [45,26],null,[45,26]);
});