define(function() {
    return {
        "properties": [{
            "name": "getDirectionIconSrc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerBackgroundSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerButtonFocusSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconScaleMode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerMainText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerSubText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerButtonSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerMainTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerSubTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "optionsFocusSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "optionsSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "separatorSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sheetBackgroundSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "travelModesForGoogleMaps",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "travelModesForAppleMaps",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iOSMapOptions",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "destinationPlaceId",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "originPlace",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "originPlaceId",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "destinationPlace",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "wayPoints",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "waypointPlaceIds",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "turnByTurnNavigation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": []
    }
});