/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
    var mappings = {
        "portfolioId": "portfolioId",
        "description": "description",
        "holdingsType": "holdingsType",
        "quantity": "quantity",
        "marketPrice": "marketPrice",
        "costPrice": "costPrice",
        "marketValue": "marketValue",
        "unrealPLMkt": "unrealPLMkt",
        "secCCy": "secCCy",
        "navPage": "navPage",
        "ISIN": "ISIN",
        "sortBy": "sortBy",
        "searchByInstrumentName": "searchByInstrumentName",
        "holdingsId": "holdingsId",
        "transactionId": "transactionId",
        "orderType": "orderType",
        "exchangeRate": "exchangeRate",
        "limitPrice": "limitPrice",
        "netAmount": "netAmount",
        "tradeDate": "tradeDate",
        "fees": "fees",
        "valueDate": "valueDate",
        "referenceCurrency": "referenceCurrency",
        "startDate": "startDate",
        "endDate": "endDate",
        "instrumentId": "instrumentId",
        "RICCode": "RICCode",
        "customerId": "customerId",
        "instrumentCurrency": "instrumentCurrency",
        "instrumentAmount": "instrumentAmount",
        "total": "total",
        "sortType": "sortType",
        "userId": "userId",
        "fieldOrder": "fieldOrder",
        "limit": "limit",
        "offset": "offset",
        "sortOrder": "sortOrder",
        "pageSize": "pageSize",
        "pageOffset": "pageOffset",
        "accountIds": "accountIds",
    };
    Object.freeze(mappings);
    var typings = {
        "portfolioId": "string",
        "description": "string",
        "holdingsType": "string",
        "quantity": "string",
        "marketPrice": "string",
        "costPrice": "string",
        "marketValue": "string",
        "unrealPLMkt": "string",
        "secCCy": "string",
        "navPage": "string",
        "ISIN": "string",
        "sortBy": "string",
        "searchByInstrumentName": "string",
        "holdingsId": "string",
        "transactionId": "string",
        "orderType": "string",
        "exchangeRate": "string",
        "limitPrice": "string",
        "netAmount": "string",
        "tradeDate": "string",
        "fees": "string",
        "valueDate": "string",
        "referenceCurrency": "string",
        "startDate": "string",
        "endDate": "string",
        "instrumentId": "string",
        "RICCode": "string",
        "customerId": "string",
        "instrumentCurrency": "string",
        "instrumentAmount": "string",
        "total": "string",
        "sortType": "string",
        "userId": "string",
        "fieldOrder": "string",
        "limit": "string",
        "offset": "string",
        "sortOrder": "string",
        "pageSize": "string",
        "pageOffset": "string",
        "accountIds": "string",
    }
    Object.freeze(typings);
    var primaryKeys = ["portfolioId", ];
    Object.freeze(primaryKeys);
    var config = {
        mappings: mappings,
        typings: typings,
        primaryKeys: primaryKeys,
        serviceName: "WealthObjects",
        tableName: "Portfolio"
    };
    Object.freeze(config);
    return config;
})