/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"Transaction_id": "Transaction_id",
		"dbpErrCode": "dbpErrCode",
		"dbpErrMsg": "dbpErrMsg",
		"opstatus": "opstatus",
		"httpStatusCode": "httpStatusCode",
		"amount": "amount",
		"frequencyEndDate": "frequencyEndDate",
		"frequencyType": "frequencyType",
		"fromAccountNumber": "fromAccountNumber",
		"isScheduled": "isScheduled",
		"scheduledDate": "scheduledDate",
		"toAccountNumber": "toAccountNumber",
		"transactionsNotes": "transactionsNotes",
		"transactionType": "transactionType",
		"transactionCurrency": "transactionCurrency",
		"MFAAttributes": "MFAAttributes",
		"serviceName": "serviceName",
		"fromAccountCurrency": "fromAccountCurrency",
		"toAccountCurrency": "toAccountCurrency",
		"numberOfRecurrences": "numberOfRecurrences",
		"p2pContact": "p2pContact",
		"personId": "personId",
		"deliverBy": "deliverBy",
		"zipCode": "zipCode",
		"billerId": "billerId",
		"billid": "billid",
		"payeeId": "payeeId",
		"payeeAccountNumber": "payeeAccountNumber",
		"payeeAddressLine1": "payeeAddressLine1",
		"payeeName": "payeeName",
		"payeeNickName": "payeeNickName",
		"payeeCurrency": "payeeCurrency",
		"wireAccountType": "wireAccountType",
		"bankName": "bankName",
		"routingNumber": "routingNumber",
		"cityName": "cityName",
		"state": "state",
		"bankAddressLine1": "bankAddressLine1",
		"bankAddressLine2": "bankAddressLine2",
		"bankCity": "bankCity",
		"bankState": "bankState",
		"bankZip": "bankZip",
		"payeeType": "payeeType",
		"payeeAddressLine2": "payeeAddressLine2",
		"swiftCode": "swiftCode",
		"country": "country",
		"internationalRoutingCode": "internationalRoutingCode",
		"frequencyStartDate": "frequencyStartDate",
		"message": "message",
		"status": "status",
		"bulkPayString": "bulkPayString",
		"referenceId": "referenceId",
		"errmsg": "errmsg",
		"initiationId": "initiationId",
		"mfaType": "mfaType",
		"transactionId": "transactionId",
		"confirmationNumber": "confirmationNumber",
		"iban": "iban",
		"wireTemplateExecution_id": "wireTemplateExecution_id",
		"bicCode": "bicCode",
		"BulkWireExecutionDetails": "BulkWireExecutionDetails",
		"bankId": "bankId",
		"feeCurrency": "feeCurrency",
		"beneficiaryName": "beneficiaryName",
		"paidBy": "paidBy",
		"paymentType": "paymentType",
		"feeAmount": "feeAmount",
		"beneficiaryAddressNickName": "beneficiaryAddressNickName",
		"beneficiaryAddressLine1": "beneficiaryAddressLine1",
		"beneficiaryCity": "beneficiaryCity",
		"beneficiaryZipcode": "beneficiaryZipcode",
		"beneficiarycountry": "beneficiarycountry",
		"backendReferenceId": "backendReferenceId",
		"checkDateOfIssue": "checkDateOfIssue",
		"checkImage": "checkImage",
		"checkImageBack": "checkImageBack",
		"toAccountType": "toAccountType",
		"profileId": "profileId",
		"uploadedattachments": "uploadedattachments",
		"validate": "validate",
		"overrides": "overrides",
		"charges": "charges",
		"exchangeRate": "exchangeRate",
		"totalAmount": "totalAmount",
		"userId": "userId",
		"uploadMessage": "uploadMessage",
		"deletedDocuments": "deletedDocuments",
		"serviceCharge": "serviceCharge",
		"successfulUploads": "successfulUploads",
		"failedUploads": "failedUploads",
		"transactionAmount": "transactionAmount",
		"convertedAmount": "convertedAmount",
		"overrideList": "overrideList",
		"requestId": "requestId",
		"createWithPaymentId": "createWithPaymentId",
		"creditValueDate": "creditValueDate",
	};

	Object.freeze(mappings);

	var typings = {
		"Transaction_id": "string",
		"dbpErrCode": "string",
		"dbpErrMsg": "string",
		"opstatus": "string",
		"httpStatusCode": "string",
		"amount": "string",
		"frequencyEndDate": "string",
		"frequencyType": "string",
		"fromAccountNumber": "string",
		"isScheduled": "string",
		"scheduledDate": "string",
		"toAccountNumber": "string",
		"transactionsNotes": "string",
		"transactionType": "string",
		"transactionCurrency": "string",
		"MFAAttributes": "string",
		"serviceName": "string",
		"fromAccountCurrency": "string",
		"toAccountCurrency": "string",
		"numberOfRecurrences": "string",
		"p2pContact": "string",
		"personId": "string",
		"deliverBy": "string",
		"zipCode": "string",
		"billerId": "string",
		"billid": "string",
		"payeeId": "string",
		"payeeAccountNumber": "string",
		"payeeAddressLine1": "string",
		"payeeName": "string",
		"payeeNickName": "string",
		"payeeCurrency": "string",
		"wireAccountType": "string",
		"bankName": "string",
		"routingNumber": "string",
		"cityName": "string",
		"state": "string",
		"bankAddressLine1": "string",
		"bankAddressLine2": "string",
		"bankCity": "string",
		"bankState": "string",
		"bankZip": "string",
		"payeeType": "string",
		"payeeAddressLine2": "string",
		"swiftCode": "string",
		"country": "string",
		"internationalRoutingCode": "string",
		"frequencyStartDate": "string",
		"message": "string",
		"status": "string",
		"bulkPayString": "string",
		"referenceId": "string",
		"errmsg": "string",
		"initiationId": "string",
		"mfaType": "string",
		"transactionId": "string",
		"confirmationNumber": "string",
		"iban": "string",
		"wireTemplateExecution_id": "string",
		"bicCode": "string",
		"BulkWireExecutionDetails": "string",
		"bankId": "string",
		"feeCurrency": "string",
		"beneficiaryName": "string",
		"paidBy": "string",
		"paymentType": "string",
		"feeAmount": "string",
		"beneficiaryAddressNickName": "string",
		"beneficiaryAddressLine1": "string",
		"beneficiaryCity": "string",
		"beneficiaryZipcode": "string",
		"beneficiarycountry": "string",
		"backendReferenceId": "string",
		"checkDateOfIssue": "string",
		"checkImage": "string",
		"checkImageBack": "string",
		"toAccountType": "string",
		"profileId": "string",
		"uploadedattachments": "string",
		"validate": "string",
		"overrides": "string",
		"charges": "string",
		"exchangeRate": "string",
		"totalAmount": "string",
		"userId": "string",
		"uploadMessage": "string",
		"deletedDocuments": "string",
		"serviceCharge": "string",
		"successfulUploads": "string",
		"failedUploads": "string",
		"transactionAmount": "string",
		"convertedAmount": "string",
		"overrideList": "string",
		"requestId": "string",
		"createWithPaymentId": "string",
		"creditValueDate": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"Transaction_id",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "TransactionObjects",
		tableName: "Transaction"
	};

	Object.freeze(config);

	return config;
})