define(function() {
    return {
        "properties": [{
            "name": "serviceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceNameDel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "separatorSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "retailIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnSwipableAction1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "alertMessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noRecordsText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "listArray",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchFields",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectNameDel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "primaryFieldSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "combinedUserIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnSwipableAction2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "yesLabelText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noSearchResultsFoundText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "listIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sortBy",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationNameDel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "secondaryFieldSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "statusImage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noLabelText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "filterParams",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getCriteriaDel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noRecordsIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "percentageFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "paginatedRecords",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "currencyCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataAvailability",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberLength",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "months",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noRecordsFoundSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maxRecords",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext", "onSearch", "onFilterSelect"],
        "events": ["onRequestStart", "onRequestEnd", "getTransactionsData", "onSwipeButtonClick", "onDeleteSuccess", "onDeleteError", "onRowClick", "onFetchError"]
    }
});