/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"FileName": "FileName",
		"ACHFileID": "ACHFileID",
		"CompanyName": "CompanyName",
		"UploadedBy": "UploadedBy",
		"UpdatedDateAndTime": "UpdatedDateAndTime",
		"NumberOfDebits": "NumberOfDebits",
		"NumberOfPrenotes": "NumberOfPrenotes",
		"UploadedByID": "UploadedByID",
		"NumberOfCredits": "NumberOfCredits",
		"softDelete": "softDelete",
		"CompanyID": "CompanyID",
		"FormatTypeID": "FormatTypeID",
		"FileStatus": "FileStatus",
		"FileSize": "FileSize",
		"FileStatusID": "FileStatusID",
		"TransactionTypeID": "TransactionTypeID",
		"TotalCreditAmount": "TotalCreditAmount",
		"TotalDebitAmount": "TotalDebitAmount",
		"FileRequestType": "FileRequestType",
		"FileFormatType": "FileFormatType",
		"NumberOfRecords": "NumberOfRecords",
		"Request_id": "Request_id",
		"Approver": "Approver",
		"userName": "userName",
		"EffectiveDate": "EffectiveDate",
		"Status": "Status",
		"ReferenceID": "ReferenceID",
		"ACHFileName": "ACHFileName",
		"DebitAmount": "DebitAmount",
		"CreditAmount": "CreditAmount",
		"Contents": "Contents",
		"ACHFileFormatType_id": "ACHFileFormatType_id",
		"RequestType": "RequestType",
		"dbpErrMsg": "dbpErrMsg",
		"dbpErrCode": "dbpErrCode",
		"opstatus": "opstatus",
		"httpStatusCode": "httpStatusCode",
		"receivedApprovals": "receivedApprovals",
		"requiredApprovals": "requiredApprovals",
		"MFAAttributes": "MFAAttributes",
		"errmsg": "errmsg",
		"serviceName": "serviceName",
		"state": "state",
		"mfaType": "mfaType",
		"filterByParam": "filterByParam",
		"sortOrder": "sortOrder",
		"sortByParam": "sortByParam",
		"pageSize": "pageSize",
		"pageOffset": "pageOffset",
		"FeatureActionId": "FeatureActionId",
		"searchString": "searchString",
		"queryType": "queryType",
		"approvalAccounts": "approvalAccounts",
		"debitAccounts": "debitAccounts",
		"filterByValue": "filterByValue",
		"amICreator": "amICreator",
		"amIApprover": "amIApprover",
	};

	Object.freeze(mappings);

	var typings = {
		"FileName": "string",
		"ACHFileID": "string",
		"CompanyName": "string",
		"UploadedBy": "string",
		"UpdatedDateAndTime": "string",
		"NumberOfDebits": "string",
		"NumberOfPrenotes": "string",
		"UploadedByID": "string",
		"NumberOfCredits": "string",
		"softDelete": "string",
		"CompanyID": "string",
		"FormatTypeID": "string",
		"FileStatus": "string",
		"FileSize": "string",
		"FileStatusID": "string",
		"TransactionTypeID": "string",
		"TotalCreditAmount": "string",
		"TotalDebitAmount": "string",
		"FileRequestType": "string",
		"FileFormatType": "string",
		"NumberOfRecords": "string",
		"Request_id": "string",
		"Approver": "string",
		"userName": "string",
		"EffectiveDate": "string",
		"Status": "string",
		"ReferenceID": "string",
		"ACHFileName": "string",
		"DebitAmount": "string",
		"CreditAmount": "string",
		"Contents": "string",
		"ACHFileFormatType_id": "string",
		"RequestType": "string",
		"dbpErrMsg": "string",
		"dbpErrCode": "string",
		"opstatus": "string",
		"httpStatusCode": "string",
		"receivedApprovals": "string",
		"requiredApprovals": "string",
		"MFAAttributes": "string",
		"errmsg": "string",
		"serviceName": "string",
		"state": "string",
		"mfaType": "string",
		"filterByParam": "string",
		"sortOrder": "string",
		"sortByParam": "string",
		"pageSize": "string",
		"pageOffset": "string",
		"FeatureActionId": "string",
		"searchString": "string",
		"queryType": "string",
		"approvalAccounts": "string",
		"debitAccounts": "string",
		"filterByValue": "string",
		"amICreator": "string",
		"amIApprover": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"ACHFileID",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "ACHObjects",
		tableName: "ACHFile"
	};

	Object.freeze(config);

	return config;
})