define(function() {
    return {
        "properties": [{
            "name": "lblHeading",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblWord",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btn1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblHeading",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblDynamicWord",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeObjectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "imgCheckBoxSelected",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tbxInputWord",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblWord",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tbxDynamicInputWord",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maskingEnabled",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btn1Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "imgCheckBoxUnSelected",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "skntbxInputWord",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dvfConfig",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeEDITOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tbxInputNotice",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lookUp",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "skntbxInputWordFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "minFillMapping",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeEDITCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblCheckBoxInfo",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknBtnAction",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeEDITIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblErrorPrompt",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryCodeEnabled",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknBtnActionFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "customServiceOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "checkBox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknInputWordError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "customServiceCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionButtonBlocked",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "customServiceIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblLookUp",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblErrorPrompt",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "skntbxInputNotice",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLblCheckBoxInfo",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "skntbxInputNoticeFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": ["setContext"]
    }
});