define(function() {
    return {
        "properties": [{
            "name": "objectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknGroupHeaderLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ListArray",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "displayDisputeIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconDisputedTransaction",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnSwipeableAction1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "blockedObjServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnSwipeableAction2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ListIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "disputeProperty",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconNoRecordsAvailable",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknGroupHeaderBackground",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "blockedObjName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknPrimaryField1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "segregationDecider",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconGroupExpand",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnSwipeableAction3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "blockedOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknPrimaryField2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "criteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "segregationTypes",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "currencyCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconGroupCollapse",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "blockedCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceResponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noRecordsAvailable",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSecondaryFields",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "recordsPerPage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "blockedServiceIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRowSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataAvailability",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "blockedDataAvailability",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSegmentShadow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknAmount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["startSearch", "onCancelSearch"],
        "events": ["setContext", "getTransactionDetails", "onRequestStart", "onRequestEnd", "swipeActionBtn"]
    }
});