define(function() {
    return function(controller) {
        var accountsTransactionListNative = new kony.ui.FlexContainer(extendConfig({
            "autogrowMode": kony.flex.AUTOGROW_NONE,
            "clipBounds": true,
            "isMaster": true,
            "height": "100%",
            "id": "accountsTransactionListNative",
            "isVisible": true,
            "layoutType": kony.flex.FREE_FORM,
            "left": "0dp",
            "isModalContainer": false,
            "preShow": function(eventobject) {
                controller.AS_FlexContainer_fe08877a8dda4bca82cf0a1d48b4cebb(eventobject);
            },
            "skin": "slFbox",
            "top": "0dp",
            "width": "100%"
        }, controller.args[0], "accountsTransactionListNative"), extendConfig({}, controller.args[1], "accountsTransactionListNative"), extendConfig({}, controller.args[2], "accountsTransactionListNative"));
        accountsTransactionListNative.setDefaultUnit(kony.flex.DP);
        var segTransactionsList = new kony.ui.SegmentedUI2(extendConfig({
            "autogrowMode": kony.flex.AUTOGROW_NONE,
            "data": [
                [{
                        "imgChevron": "groupexpandicon.png",
                        "lblHeaderName": "Transaction header name"
                    },
                    [{
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }]
                ],
                [{
                        "imgChevron": "groupexpandicon.png",
                        "lblHeaderName": "Transaction header name"
                    },
                    [{
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }, {
                        "imgIcon": "norecordsavailableicon_1.png",
                        "imgIcon1": "pendingtransactionxxx.png",
                        "imgIcon2": "pendingtransactionxxx.png",
                        "imgIcon3": "pendingtransactionxxx.png",
                        "imgIcon4": "pendingtransactionxxx.png",
                        "imgSwipeBtn1": "dispute.png",
                        "imgSwipeBtn2": "dispute.png",
                        "imgSwipeBtn3": "cancel_1.png",
                        "lblField1": "Money Transfer to Linda",
                        "lblField2": "$200.00",
                        "lblField3": "12/10/2020",
                        "lblField4": "4th Field",
                        "lblNoRecords": "No Record is available.",
                        "lblSwipeBtn1Text": "Label",
                        "lblSwipeBtn2Text": "Label",
                        "lblSwipeBtn3Text": "Label"
                    }]
                ]
            ],
            "groupCells": false,
            "height": "100%",
            "id": "segTransactionsList",
            "isVisible": true,
            "left": "0dp",
            "needPageIndicator": true,
            "onRowClick": controller.AS_Segment_ba38f3958af74f0ca0a9ad05b7142b56,
            "pageOffDotImage": "pageoffdot.png",
            "pageOnDotImage": "pageondot.png",
            "retainSelection": false,
            "rowTemplate": "flxTransactionsRowTemplate",
            "scrollingEvents": {
                "onReachingEnd": controller.AS_Segment_h196540cd9704bd18121a53ec75f18cc
            },
            "sectionHeaderTemplate": "flxTransactionsHeader",
            "selectionBehavior": constants.SEGUI_DEFAULT_BEHAVIOR,
            "separatorColor": "e3e3e300",
            "separatorRequired": true,
            "separatorThickness": 1,
            "showScrollbars": false,
            "top": "0dp",
            "viewType": constants.SEGUI_VIEW_TYPE_TABLEVIEW,
            "widgetDataMap": {
                "flxField1": "flxField1",
                "flxField3": "flxField3",
                "flxGroup1": "flxGroup1",
                "flxGroup2": "flxGroup2",
                "flxGroup3": "flxGroup3",
                "flxGroup4": "flxGroup4",
                "flxIcon1": "flxIcon1",
                "flxIcon2": "flxIcon2",
                "flxIcon3": "flxIcon3",
                "flxIcon4": "flxIcon4",
                "flxImgChevron": "flxImgChevron",
                "flxNoRecords": "flxNoRecords",
                "flxRightSideContents": "flxRightSideContents",
                "flxRow": "flxRow",
                "flxSeparator": "flxSeparator",
                "flxSwipeBtn1": "flxSwipeBtn1",
                "flxSwipeBtn2": "flxSwipeBtn2",
                "flxSwipeBtn3": "flxSwipeBtn3",
                "flxSwipeContainer": "flxSwipeContainer",
                "flxTransactionsHeader": "flxTransactionsHeader",
                "flxTransactionsRowTemplate": "flxTransactionsRowTemplate",
                "flxUpShadow": "flxUpShadow",
                "imgChevron": "imgChevron",
                "imgIcon": "imgIcon",
                "imgIcon1": "imgIcon1",
                "imgIcon2": "imgIcon2",
                "imgIcon3": "imgIcon3",
                "imgIcon4": "imgIcon4",
                "imgSwipeBtn1": "imgSwipeBtn1",
                "imgSwipeBtn2": "imgSwipeBtn2",
                "imgSwipeBtn3": "imgSwipeBtn3",
                "lblField1": "lblField1",
                "lblField2": "lblField2",
                "lblField3": "lblField3",
                "lblField4": "lblField4",
                "lblHeaderName": "lblHeaderName",
                "lblNoRecords": "lblNoRecords",
                "lblSwipeBtn1Text": "lblSwipeBtn1Text",
                "lblSwipeBtn2Text": "lblSwipeBtn2Text",
                "lblSwipeBtn3Text": "lblSwipeBtn3Text"
            },
            "width": "100%",
            "zIndex": 1
        }, controller.args[0], "segTransactionsList"), extendConfig({
            "padding": [0, 0, 0, 0],
            "paddingInPixel": false
        }, controller.args[1], "segTransactionsList"), extendConfig({}, controller.args[2], "segTransactionsList"));
        var flxListLoading = new kony.ui.FlexContainer(extendConfig({
            "autogrowMode": kony.flex.AUTOGROW_NONE,
            "clipBounds": true,
            "height": "54dp",
            "id": "flxListLoading",
            "isVisible": false,
            "layoutType": kony.flex.FREE_FORM,
            "left": "0dp",
            "isModalContainer": false,
            "skin": "slFbox",
            "top": "4dp",
            "width": "101.39%",
            "zIndex": 1
        }, controller.args[0], "flxListLoading"), extendConfig({}, controller.args[1], "flxListLoading"), extendConfig({}, controller.args[2], "flxListLoading"));
        flxListLoading.setDefaultUnit(kony.flex.DP);
        var lblListLoading = new kony.ui.Label(extendConfig({
            "id": "lblListLoading",
            "isVisible": true,
            "left": "149dp",
            "skin": "sknEditChannel",
            "text": "List loading . . .",
            "textStyle": {
                "letterSpacing": 0,
                "strikeThrough": false
            },
            "top": "6dp",
            "width": kony.flex.USE_PREFFERED_SIZE,
            "zIndex": 1
        }, controller.args[0], "lblListLoading"), extendConfig({
            "contentAlignment": constants.CONTENT_ALIGN_MIDDLE_LEFT,
            "padding": [0, 0, 0, 0],
            "paddingInPixel": false
        }, controller.args[1], "lblListLoading"), extendConfig({
            "textCopyable": false
        }, controller.args[2], "lblListLoading"));
        flxListLoading.add(lblListLoading);
        accountsTransactionListNative.add(segTransactionsList, flxListLoading);
        return accountsTransactionListNative;
    }
})