define(function() {
    return {
        "properties": [{
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransDetails",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "checkNumberLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "statusFieldVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transactionTypeIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectServiceNameAttachments",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transactionType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransDetailsLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "checkNumberValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectNameAttachments",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transactionTypes",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransDetailsValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftTransaction",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "statusIndicatorVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationNameAttachments",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "currencyCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "criteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftTransactionSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "criteriaAttachments",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransDetailsAmount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enableAttachments",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransDetailsSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransStatusPending",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransStatusSuccess",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTransDetailsStatus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldStatus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field11Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field11Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field11Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field12Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "filed12Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field12Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnContextualAction1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnContextualAction2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnContextualAction3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnContextualAction4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnContextualAction5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext"],
        "events": ["onError", "getBtnEntitlement", "requestStart", "requestEnd", "contextualActionButtonOnClick", "downloadCheck", "navigateToViewAttachments"]
    }
});