define(function() {
    return {
        "properties": [{
            "name": "objectServiceName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleBgSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "checkboxSelectedImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleMsgText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "isPostLogin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleMsgSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "checkboxEmptyImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errorMsgText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "action",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errorMsgSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "submitBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enableBtnSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "registerDeviceText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "disableBtnSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "registerDeviceSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext"],
        "events": ["onSuccessCallback", "rememberDeviceRegFlag", "onFailureCallback", "onCancel"]
    }
});