define(function() {
    return {
        "properties": [{
            "name": "payeeIconVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeObjectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "responsePath",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "placeHolderSearch",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ebillVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconSearch",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "responsePathSearch",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRowHover",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeGETOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "emptyPayeesDisplayLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchFieldList",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRowSeperator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeGETCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "inPlaceHandling",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldEbill",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknField1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeGETIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pageSize",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swipeBox1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknField2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeDELETEOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swipeBox2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionButtons",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeDELETECriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swipeBox3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSearchTextBox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeDELETEIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeSearchObjectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSearchPlaceHolderTextBox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeSearchObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSearchTextBoxFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rowonClickaction",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeSEARCHOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeSEARCHCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeSEARCHIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSwipeBox1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSwipeBox2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSwipeBox3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSwipeBoxText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setParentScope", "setContext"],
        "events": ["onError"]
    }
});