define(function() {
    return {
        "properties": [{
            "name": "identityServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnTouchPinFaceIdSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "faceIDPopupImage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "touchIDBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pinPopupTitleSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pinIDBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pinPopupNumbersSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "faceIDBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pinPopupClearButtonSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pinPopupTitleText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "popupCancelButtonSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "popupCancelBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "faceIDPopupTitleSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "faceIDPopupTitleText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "faceIDPopupDescSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "faceIDPopupDescText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setVisibilityForSpecificLoginType", "initiateLoginFlow"],
        "events": ["onLoginSuccess", "onPopupVisible", "onLoginFailure"]
    }
});