define(function() {
    return {
        "properties": [{
            "name": "headerSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textVisiblityOffIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2HeaderMessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen3HeaderMessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "activationExpire",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1HeaderMessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen4HeaderMessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen5HeaderMessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textVisiblityOnIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2HeaderCancelText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen3MessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "validateService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "unableToVerify",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1HeaderCancelText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen4HeaderCancelText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen5MessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerCancelButtonSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tickGrayIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2MessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen3DescriptionText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordUpdateService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "unableToUpdate",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1DescriptionText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen4Label1Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen5DescriptionText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tickGreenIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2Label1Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen3SubmitBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordPolicyService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1ErrorMessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen4Textbox1PlaceholderText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen5SubmitBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordObjModelName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errorMessageSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successTickIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2Textbox1PlaceholderText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1TextBox1PlaceholderText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen4Label2Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "deviceProvisioningService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBoxNormalSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2Label2Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1TextBox2PlaceholderText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen4Textbox2PlaceholderText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen4LabelPasswordRulesText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBoxErrorSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2Textbox2PlaceholderText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1SubmitBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "buttonEnabledSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2LabelPasswordRulesText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1ForgetPasswordBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen4SubmitBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "buttonDisabledSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2SubmitBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen4MessageText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "forgetPasswordSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2MessageSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "labelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordRulesLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "passwordRulesSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen3MessageSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBoxNormalFocusSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["navigateToScreen", "registerPushId"],
        "events": ["navigateToLogin", "closeActivateProfileFlow"]
    }
});