define(function() {
    return {
        "properties": [{
            "name": "keySkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldCount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "valueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Key",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionButtonSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Key",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberMasking",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Key",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Key",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5Key",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6Key",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7Key",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8Key",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext", "setParentScope", "setEntitlements"],
        "events": ["onError"]
    }
});