define(function() {
    return {
        "properties": [{
            "name": "fromAccountObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fromAccountsTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknHeaderLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFromLblAmtScrn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toAccountsTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "currencyPageTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "paymentMethodTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleBICSwiftCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftLookupHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleRequiredCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleCalenderSendOn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifySectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleAddAddress",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toAccObjServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cancelButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountLable1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "frequencyPageTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "feesPaidTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleReferenceLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleIntermediaryBIC",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleE2ERef",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleRecipientName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleAccountNumber",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titlePayeeNickname",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titlePayeeNicknameSuccess",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contactTypeTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryCodeTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconActive",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transferType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dvfConfig",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryObjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblCalenderDate",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transferTypes",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputSendOn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "segregationTypes",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "calenderContinueBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountTypesList",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "flowType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftSrchObjServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ValObjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "DateObjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sendOnDateLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addressObjectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "IBANObjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getBeneficiaryService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblSupportingDocuments",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "creditcardObjServName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "IBANSwiftObjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "valOTTobjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "OTTserviceResponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "CCObjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "loanCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftSrchObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fromAccountOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fromdescriptionLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFromValueAmtScrn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "todescriptionLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dropdownTransferCurrency",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblPaymentMethod",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftLookupDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "requiredCodeLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFromLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblAddAddress",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toAccObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknHeaderBg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchProperties",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountValue1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dropdownFrequency",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblFeesPaidBy",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblfxRateReference",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblIntermediaryBIC",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblE2ERef",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblRecipientName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblAccountNumber",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblPayeeNickname",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblPayeeNicknameSuccess",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countrySearchProperty",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconAdd",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "minAmount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transObjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "listBoxDropDownImage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contactTypeDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ValObjName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "DateObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "startDateLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "IBANObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getBeneficiaryObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectedFileValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "creaditcardObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "IBANSwiftObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "valOTTcriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "OTTobjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "CCObjectname",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transferTypePermission",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "loanObjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "supportedFileFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblMobileNumber",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblBICSwiftCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftSrchOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fromField1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fromAccountsCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "defaultFrequency",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFromBalanceLblAmtScrn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toField1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "paymentMethodOption1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputBICSwiftCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchField1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftSrchCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "requiredCodeField1Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFromValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField1Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toAccOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknCancelBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblEmptyRecord",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountLable2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "feesPaidOption1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputfxRateReference",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputIntermediaryBIC",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputE2ERef",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputRecipientName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReEnterAccountNumber",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputPayeeNickname",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblPayeeNicknameSuccessDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconRightArrow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryFlagVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getCountriesOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ValCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "DateOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "endDateLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "IBANCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getBeneficiaryOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "creditcardOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "IBANSwiftOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "valOTTobjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "OTTobjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "CCoperationname",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "loanObjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputMobileNumber",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fromField2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fromServiceResponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFromBalanceValueAmtScrn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toField2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "paymentMethodOption2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnBICSwiftCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchField1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftSrchServiceResIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "requiredCodeField1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFromBalanceLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toAccCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSearchBox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountValue2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "feesPaidOption2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "referenceBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "IntermediaryBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "E2EBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputAccountNumber",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeNicknameBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeNicknameNewTransfer",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconBack",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "recipientRestrictChars",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ValOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getCountriesCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "DateCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "IBANOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getBeneficiaryCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iphoneFileExtension",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "creditcardCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "IBANSwiftCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "valOTTserviceResponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "OTTcriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectedDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "CCServiceResponseIdenfier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "loanOperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fileSize",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "recipientBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblEmail",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fromField3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldToLabelAmtScrn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toField3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "paymentMethodOption3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnBICSWIFTLookup",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchField2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "requiredCodeField2Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFromBalanceValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField2Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toAccServiceResIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSearchTextArea",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountLable3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "feesPaidOption3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputReEnterAccountNumber",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeNicknameTransferActivities",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconBusiness",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fromObjectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transServiceResponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ValServiceResponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getCountriesIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "DateServiceResponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "creditcardResponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bankNameKeyIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "valOTToperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "OTToperationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "daysToRestrict",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "CCcriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputEmail",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fromField4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldToValueAmtScrn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toField4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "paymentMethodOption4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchField2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "requiredCodeField2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldToLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknDescriptionBg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountValue3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconCalenderArrowLeft",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblBICSwiftQuestion",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "defaultFeesPaidBy",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "statesObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "currentServiceBankDate",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectOption1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "countryServiceIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftCodeKeyIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateContinue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "filterTypeList",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phoneNumberChooseBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldToBalanceLblAmtScrn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "toAccountBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchField3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "requiredCodeField3Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldToValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField3Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknDescriptionLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "otherAmountLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconCalenderArrowRight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accNumErrorMessage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "defaultPaymentMethod",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getStatesOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectOption2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceFeesPaidValues",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enableBankDate",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldToBalanceValueAmtScrn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchField3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "requiredCodeField3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldToBalanceLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknDescriptionSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "otherAmountValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconCancelKeypad",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "paymentMethodOption5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getStatesCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "reEnterAccNumErrorMessage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contactOROption",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceDefaultFeesPaid",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectOption3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldToBalanceValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "emailChooseBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "otherAmtBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblTransferCurrency",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchField4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "requiredCodeBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField4Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "paymentMethodOption6",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getStatesIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknGroupHeaderLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconChevron",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectOption4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberExistMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "otherAmtHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transferCurrency",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchField4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "swiftBICBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknGroupHeaderBg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconChevronRight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contactEmailError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cancelOption",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberNotMatch",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "servicePaymentMethodValues",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contactTypeBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblTransferAmount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getDetailsBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "clearingCode1Btn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField5Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknPrimaryField1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconChevronWhiteLeft",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceDefaultPaymentMethod",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtInputTransferAmount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblSwiftSearchResult",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "clearingCode2Btn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField5Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknPrimaryField2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconChevronWhiteRight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "removeDocsTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchResultValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField6Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSecondaryFields",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconClear",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sizepopupTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField6Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRowSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconConfirmationTick",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnUseSwift",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "popupActionbtns",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "transferAmountHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fileSizeError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField7Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconCurrencySelection",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "researchSwiftBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fileTypeError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField7Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSegmentShadow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconDownload",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField8Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknDisabledContexualBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconConfirmationError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField5Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressField8Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknInputBoxPlaceholder",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconGroupExpand",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField5Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknInputBoxBorder",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconGroupCollapse",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField6Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "boxSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconInactive",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField6Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectedBoxSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconInfo",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField7Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconSearch",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField7Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "descriptionSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField8Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lookUpSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconPersonal",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addAddressErrorMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField8Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successLabelSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconSelectGrnTick",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "addressRestrictCharacterSet",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField9Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errorValidationSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "businessIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phoneNumberRestrictCharacterSet",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField9Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknEnableContexualBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "retailIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "citiBankImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknQuestionLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField10Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "chaseBankImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField10Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBoxNormalSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "boaBankImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField11Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBoxErrorSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "hdfcBankImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField11Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSegOptionSelected",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknVerifyFieldLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "infinityBankImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField12Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSegOptionNotSelected",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknVerifyFieldValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "externalBankImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField12Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknVerifyChargesValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "listBoxSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField13Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSegCurrencyValues",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconSearchClose",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "listBoxFocusSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFeesPaidOptionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField13Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "listBoxPlaceHolderSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFeesPaidOptionDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField14Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField14Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subTitleSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField15Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accNumInputLineSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField15Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accNumInputFieldSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField16Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "reEnterAccNumInputFieldSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField16Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknCameraWidget",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField17Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSelectOption",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField17Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSupportingActionBtns",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField18Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRemoveSupportingDocsTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField18Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSupportingTextHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknPopupCloseButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknPopupCancelButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFlexNormal",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknHighlightedFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknVerifyBalanceValues",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknhighlightedDate",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyTransferBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknCurrencyselection",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyNotesLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyNotesValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyBeneAddLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyBeneMobile",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyBeneZipcode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyBeneCountry",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyBeneAddLine1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyBeneCity",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyBeneEmail",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyBeneState",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyBeneAddLine2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField5Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField5Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField6Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField6Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField7Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField7Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField8Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReadOnlyField8Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext", "goBack", "onVerifyDetailsBack", "dateBackNavigation"],
        "events": ["onRequestStart", "onRequestEnd", "onBackButtonClick", "createTransSuccessCallback", "iPhoneHeaderProps"]
    }
});