define(function() {
    return {
        "properties": [{
            "name": "cifObjectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contractSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeaderLabel1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "button1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknContentFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cifObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contractListTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeaderLabel2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectAllBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknHeadingBg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cifOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contractListArrayKey",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "deselectAllBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknDatagridHeadingLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconCheckboxSelected",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeaderContractId",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "customerListTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cifCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectedTextContract",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnDone",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknCancelBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconCheckboxUnSelected",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectedTextCustomer",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cifIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contractDataGridLabel1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSubhdrBg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconBusinessPayeeIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "selectedCustomerCount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contractDataGridLabel2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSubhdrTxt",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconpersonalPayee",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "customerListArrayKey",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSelectedSubhdrVal1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconRightArrow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "customerDataGridLabel1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSelectedSubhdrVal2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconBack",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "customerDataGridLabel2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSubhdrSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "businessIconCondition",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSelectedCountSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "retailIconCondition",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSelectDeselectAll",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSelectHeaderRowSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknParentRow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknChildRow",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknParentLayerValue1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknParentLayerValue2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknChildLayerValue1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknChildLayerValue2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionBtnDisabled",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionBtnFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext"],
        "events": ["onLinkPayeeContinue"]
    }
});