/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"bulkWireTransactionID": "bulkWireTransactionID",
		"bulkWireFileID": "bulkWireFileID",
		"initiatedBy": "initiatedBy",
		"transactionDate": "transactionDate",
		"totalCountOfTransactions": "totalCountOfTransactions",
		"createdts": "createdts",
		"lastmodifiedts": "lastmodifiedts",
		"totalCountOfDomesticTransactions": "totalCountOfDomesticTransactions",
		"totalCountOfInternationalTransactions": "totalCountOfInternationalTransactions",
		"dbpErrMsg": "dbpErrMsg",
		"dbpErrCode": "dbpErrCode",
		"searchString": "searchString",
		"sortByParam": "sortByParam",
		"sortOrder": "sortOrder",
		"pageOffset": "pageOffset",
		"pageSize": "pageSize",
		"referenceId": "referenceId",
		"initiationId": "initiationId",
		"transactionId": "transactionId",
		"confirmationNumber": "confirmationNumber",
		"message": "message",
		"companyId": "companyId",
		"requestId": "requestId",
		"status": "status",
		"featureActionId": "featureActionId",
		"onetime_id": "onetime_id",
		"wireFileExecution_id": "wireFileExecution_id",
		"transactionts": "transactionts",
		"notes": "notes",
		"amount": "amount",
		"fromAccountNumber": "fromAccountNumber",
		"payeeAccountNumber": "payeeAccountNumber",
		"transactionType": "transactionType",
		"payeeId": "payeeId",
		"payeeCurrency": "payeeCurrency",
		"payeeName": "payeeName",
		"payeeNickName": "payeeNickName",
		"payeeType": "payeeType",
		"wireAccountType": "wireAccountType",
		"swiftCode": "swiftCode",
		"routingNumber": "routingNumber",
		"zipCode": "zipCode",
		"cityName": "cityName",
		"state": "state",
		"country": "country",
		"payeeAddressLine1": "payeeAddressLine1",
		"payeeAddressLine2": "payeeAddressLine2",
		"bankName": "bankName",
		"internationalRoutingCode": "internationalRoutingCode",
		"bankAddressLine1": "bankAddressLine1",
		"bankAddressLine2": "bankAddressLine2",
		"bankCity": "bankCity",
		"bankState": "bankState",
		"bankZip": "bankZip",
		"International": "International",
		"Domestic": "Domestic",
		"BulkWireFileExecutionDetails": "BulkWireFileExecutionDetails",
		"BulkWireFileExecution_id": "BulkWireFileExecution_id",
		"statusFilter": "statusFilter",
		"totalCount": "totalCount",
		"successCount": "successCount",
		"failedCount": "failedCount",
		"pendingCount": "pendingCount",
		"firstname": "firstname",
		"lastname": "lastname",
		"BulkWireTemplateExecution_id": "BulkWireTemplateExecution_id",
		"BulkWireTemplateExecutionDetails": "BulkWireTemplateExecutionDetails",
		"BulkWireTemplateTransactDetails": "BulkWireTemplateTransactDetails",
		"bulkWireTemplateID": "bulkWireTemplateID",
	};

	Object.freeze(mappings);

	var typings = {
		"bulkWireTransactionID": "number",
		"bulkWireFileID": "number",
		"initiatedBy": "string",
		"transactionDate": "string",
		"totalCountOfTransactions": "number",
		"createdts": "string",
		"lastmodifiedts": "string",
		"totalCountOfDomesticTransactions": "number",
		"totalCountOfInternationalTransactions": "number",
		"dbpErrMsg": "string",
		"dbpErrCode": "string",
		"searchString": "string",
		"sortByParam": "string",
		"sortOrder": "string",
		"pageOffset": "string",
		"pageSize": "string",
		"referenceId": "string",
		"initiationId": "string",
		"transactionId": "string",
		"confirmationNumber": "string",
		"message": "string",
		"companyId": "string",
		"requestId": "string",
		"status": "string",
		"featureActionId": "string",
		"onetime_id": "string",
		"wireFileExecution_id": "string",
		"transactionts": "string",
		"notes": "string",
		"amount": "number",
		"fromAccountNumber": "string",
		"payeeAccountNumber": "string",
		"transactionType": "string",
		"payeeId": "string",
		"payeeCurrency": "string",
		"payeeName": "string",
		"payeeNickName": "string",
		"payeeType": "string",
		"wireAccountType": "string",
		"swiftCode": "string",
		"routingNumber": "string",
		"zipCode": "string",
		"cityName": "string",
		"state": "string",
		"country": "string",
		"payeeAddressLine1": "string",
		"payeeAddressLine2": "string",
		"bankName": "string",
		"internationalRoutingCode": "string",
		"bankAddressLine1": "string",
		"bankAddressLine2": "string",
		"bankCity": "string",
		"bankState": "string",
		"bankZip": "string",
		"International": "string",
		"Domestic": "string",
		"BulkWireFileExecutionDetails": "string",
		"BulkWireFileExecution_id": "string",
		"statusFilter": "string",
		"totalCount": "number",
		"successCount": "number",
		"failedCount": "number",
		"pendingCount": "number",
		"firstname": "string",
		"lastname": "string",
		"BulkWireTemplateExecution_id": "string",
		"BulkWireTemplateExecutionDetails": "string",
		"BulkWireTemplateTransactDetails": "string",
		"bulkWireTemplateID": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"bulkWireTransactionID",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "BulkWireObjects",
		tableName: "BulkWireTransaction"
	};

	Object.freeze(config);

	return config;
})