define(function() {
    return {
        "properties": [{
            "name": "objectServiceName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectServiceName2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectServiceName3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectServiceName4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": []
    }
});