define(function() {
    return {
        "properties": [{
            "name": "objectServiceName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectServiceName2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1SubmitBtnEnabledSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2TitleBgSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1SubmitBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2TitleText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "checkboxSelectedImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "action",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen1SubmitBtnDisabledSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2TitleSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2SubtitleText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "checkboxUnselectedImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "isPostLogin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2SubtitleSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2DescriptionText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2DescriptionSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2ErrorMsgText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2ErrorMsgSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2ResendBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2ResendBtnSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2RegisterDevLblText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2RegisterDevLblSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2SubmitBtnText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2SubmitBtnEnabledSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "screen2SubmitBtnDisabledSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext"],
        "events": ["rememberDeviceRegFlag", "onSuccessCallback", "onFailureCallback", "onCancel"]
    }
});