define(function() {
    return {
        "properties": [{
            "name": "gsknbillpayHeaderFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fassSearchBox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ptssknSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "acnSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "acnsSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntsFlexRowBG",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lnSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lnsFlexRowBG",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssRowBG",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdsSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "brSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "brSknSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dvfConfig",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rfpSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rfpsSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fadsFlexBg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fadFromLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errsErrorHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errsTitleMessage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasObjService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fassSubheader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ptssknTxtbxLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "acnSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "acnsTxtbx",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntField1Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntsLableSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lntField1Val",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lnsFiled1skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdsLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "brSubHeaderTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "brSknSubHeaderSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ptSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gskBillpaynHeaderLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "minFillMapping",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rfpTxbxLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rfpsTxtbxLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "paymentType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdObjService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fadBalanceLable",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fadsFromLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errsSubTitile",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdObjName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billpayimgBack",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ptSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasObjOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fassSegmentHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ptssknTxtbx",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntField1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntsSubValue1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lnCTA1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssValueEditableSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdsValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "brSknSelectedCTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknBillpayCancelBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maxFillMapping",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rfpsTxtbx",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fadBalanceValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fadsAccountName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "acnShowFromAccount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rfpShowFromAccount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "acnsTbxHeaderLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errsFailIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fadAccountName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billpaybtnCancel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknbillpayContentFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ptShowFromAccount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasObjOperationCreteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fassSegHeaderBG",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntField1SubLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntsSubValue2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdObjOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssValueReadonlySkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdsLabelEdit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "brSknUnselectedCTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "jsonObjName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fadsBalanceLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "acnTbxHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rfpTbxHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errsCTA1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "acnTextbox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billpayFormOrder3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasGetFromAccountResponse",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fassField1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntField1SubValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntsTxtbxLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdObjOperationCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssSubLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdGetBillPayeeDetails",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdsValueEdittbx",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknbillpaySubhdrFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "brdropdownOptions",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "brSknOptionSelection",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rfpTextboxType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fadsBalanceValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ptTbxHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errsCTA2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rfpTxtbx",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "acnCTA1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billpayFormOrder4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ptTextbox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fassField2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntTxtbxLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntsInput",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssSubValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdsSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknSubhdrSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "brShowFromAccount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rfpCTA1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billpayFormOrder5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknbillpayErrorTextMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ptCTA1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasSearchBox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fassField3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntTxtbx",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntDollarLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssRowSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdSubHeaderEdit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errscreenCTA3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errsCTA3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ptErrTxtbx",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billpayFormOrder6",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fassField4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntCTA1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntAmountLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField1SubLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssNotesRealAll",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdShowFromAccount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknTxtboxErr",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknTextBoxFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billpayLoadingIndicator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasAccSegregationType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fassRowSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField1SubValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssNotes",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdLabel1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntZeroBalWarnMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntsTxtboxSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknPrimaryContexualBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "BillpayInterstialScreenText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasSegmentTemplate",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdValue1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntinsufficientMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknSecondaryContexualBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "BillpayErrorReporting",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasAccListArray",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdLabel1Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amntFormatAmount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknDisabledContexualBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasAccListIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdValue1Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknBillpayNumericKeypad",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "inputValuesPool",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasField1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdLabel2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknBillPayKeypadGrey",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasField2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdValue2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "billpayEdit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknBillpayNumericKeypadBorder",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasField3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdLabel2Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasField4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField5Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdValue2Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknErrorScreenTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasBizIconCondition",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdLabel3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField5Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknErrorScreenDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField6Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasBizIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdValue3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField6Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasRtIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdLabel3Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField7Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasSegCollapseIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdValue3Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField7Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasSegExpandIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdLabel4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField8Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdValue4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "AccTypedataPermsn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField8Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdLabel4Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "filterTypeList",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField9Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdValue4Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fasSearchBoxVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField9Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdLabel5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchicon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsImgEdit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdValue5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdLabel5Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsLegalNotesType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsFieldNotes",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdValue5Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsFieldNotesMoreLink",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdCTA1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsLegalNotes",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdCTA2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsLegalNotesDesc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdCTA3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsCTA1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdCTAEditAddress",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsCTA2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdObjService1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdObjName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdObjOperation1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bpdObjOperation1Criteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsfesibilityFailMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsAmoutValidationErrMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsImgWarn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField10Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "verifyField10Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfserrortype",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsShowLessLink",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "imgFromChevron",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext", "enableCancelPopup", "goBack", "onVerifyDetailsBack"],
        "events": ["backNav", "onVerifySuccessCallBack", "iPhoneHeaderProps", "onAccountsDashBoardNav"]
    }
});