define(function() {
    return {
        "properties": [{
            "name": "fieldOneValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noRecordsFoundText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldOneKey",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "topFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "totalValueKey",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "referenceCurrency",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "featuresAndPermission",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldTwoValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "placeholderSearchText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "totalValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldThreeValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFourKey",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "orderToggleIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldThreeKey",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "requestParam",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFiveValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFiveKey",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceResponseKey",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFourValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rowSeperatorSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldOneValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFiveValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldThreeValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldTwoValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFourValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldIdOne",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionImgSrc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "logoImgSrc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "logoIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionImgIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldOneType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldThreeType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFiveType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldFourType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldTwoType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "currencyCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldTwoKey",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldIdTwo",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "allFieldKeySkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "orderStatusIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "statusImgSrc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "statusText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["removeAll", "setContext", "setLblPreviousDays", "getPreviousDaysText", "getCriteriaObjValue", "getRefCurrency", "setCashAccounts", "cancelOrder", "callOrderHistory", "onActionSelect", "setCriteriaObjectValue", "setEuroFlow", "getFeaturesAndPermissions", "setVisibleActionImage", "getHoldingsTopDetails"],
        "events": ["preShow", "onActionButtonClicked", "onRowClickEvent", "onMoveToDateRange", "onClickOpenOrders", "onClickOrderHistory", "onRequestStart", "onRequestEnd", "onMoveToCashAccounts", "onOrdersComponentLoad"]
    }
});