struct Constants {
  static let ERROR_FORM = "frmError"
  static let DASHBOARD_FORM = "frmDashboard"
  static let REQUEST_KEY = "request"
  static let FETCH_ACCOUNT_REQUEST = "fetchAccounts"
  static let FETCH_TRANSACTION_REQUEST = "fetchTransactions"
  static let TRANSACTION_FORM = "frmTransactions"
  static let ACCOUNT_TEMPLATE_TYPE = "tempAccounts"
  static let PENDING_TRANSACTION_TEMPLATE_TYPE = "tempPendingTransactions"
  static let POSTED_TRANSACTION_TEMPLATE_TYPE = "tempPostedTransactions"

  static let KEY_CURRENT_BALANCE = "currentBalance"
  static let KEY_OUT_BALANCE = "outstandingBalance"
  static let KEY_AVAILABLE_BALANCE = "availableBalance"
  static let KEY_DUE_DATE =  "dueDate"
  static let KEY_MATURITY_DATE =  "maturityDate"
  static let KEY_MINIMUM_DUE = "minimumDue"
  static let KEY_UPCOMING_BILL = "lastStatementBalance"
  static let KEY_CURRENT_DUE = "currentAmountDue"
  static let KEY_PRINCIPAL_BALANCE = "principalBalance"

  static let ACCOUNT_TYPE_DEPOSIT = "Deposit"
  static let ACCOUNT_TYPE_SAVINGS = "Savings"
  static let ACCOUNT_TYPE_CHECKING = "Checking"
  static let ACCOUNT_TYPE_CREDIT_CARD = "CreditCard"
  static let ACCOUNT_TYPE_LOAN = "Loan"
  static let ACCOUNT_TYPE_CURRENT = "Current"

  static let ZERO_BALANCE = "0.00"
  static let LOADER_IMAGE_INITIAL = "Loader"
  static let NEGATIVE_SIGN = "-"
  static let PAYOFF_BALANCE_TEXT = "Payoff Balance"
  static let PAYMENT_AMOUNT_TEXT = "Payment Amount"
  static let ERROR = "error"
}

