define(function() {
    return {
        "properties": [{
            "name": "componentVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "placeholderText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSearchText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "imgSearchIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "advancedFilterValues",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSearchTextPlaceholderBox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "closeFilterIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFilterHeading",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "imgFilterIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "filterSelected",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSearchTextboxFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "AdvancedFilterselectedDataIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "showAllButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFilterListData",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cancelSearchIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSearchAndFilterBackground",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFilteredDataHeaderBackground",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFilterListHeaderBackground",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": ["onSearchTextChange", "onFilterSelect", "onError"]
    }
});