define(function() {
    return {
        "properties": [{
            "name": "titleTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "visibleTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "visibleTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "visibleTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountTypeContextPath",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bankNameSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maskingRequired",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "nickName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "currencyCodeContextPath",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titleTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1LabelTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tabHeaderSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1LabelTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1LabelTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1LabelTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1ValueTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "labelNameSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "userTypeContextPath",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maskVizIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noOfEllipsis",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1TypeTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1ValueTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1ValueTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "criteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1ValueTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "defaultValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "unmaskVizIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noOfCharacters",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2LabelTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1TypeTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1TypeTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1TypeTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "businessAccount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2ValueTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2LabelTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2LabelTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2LabelTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "percentageValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2ValueTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2TypeTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2ValueTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2ValueTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "positiveValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3LabelTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2TypeTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2TypeTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2TypeTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "negativeValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3ValueTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3LabelTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3LabelTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3LabelTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3TypeTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3ValueTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3ValueTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3ValueTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maskIconSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "unmaskIconSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4LabelTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3TypeTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3TypeTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3TypeTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4LabelTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4ValueTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4LabelTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4LabelTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "buttonSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4ValueTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4TypeTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4ValueTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4ValueTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "editLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4TypeTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5LabelTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4TypeTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4TypeTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pageHeaderLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5LabelTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5ValueTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5LabelTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5LabelTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerBgSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5ValueTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5TypeTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5ValueTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5ValueTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "bankNameBGSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5TypeTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6LabelTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5TypeTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5TypeTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tabHeaderBGSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6LabelTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6LabelTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6LabelTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6ValueTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tabDetailsBGSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6TypeTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6ValueTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6ValueTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6ValueTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7LabelTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6TypeTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6TypeTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6TypeTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7ValueTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7LabelTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7LabelTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7LabelTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7TypeTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7ValueTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7ValueTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7ValueTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7TypeTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8LabelTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7TypeTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7TypeTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8LabelTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8ValueTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8LabelTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8LabelTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8ValueTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8TypeTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8ValueTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8ValueTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8TypeTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9LabelTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8TypeTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8TypeTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9LabelTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9ValueTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9LabelTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9LabelTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9ValueTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9TypeTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9ValueTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9ValueTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9TypeTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10LabelTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9TypeTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9TypeTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10LabelTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10ValueTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10LabelTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10LabelTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10ValueTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10TypeTab1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10ValueTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10ValueTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10TypeTab2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10TypeTab3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10TypeTab4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext", "setUserContext"],
        "events": ["onError", "requestStart", "requestEnd", "onContactUsButtonClick"]
    }
});