it("ManageRecipient_AddaRecipient_Externalbank", async function() {
	await kony.automation.playback.waitFor(["frmManageRecipientType","segRecipientType"]);
	kony.automation.segmentedui.click(["frmManageRecipientType","segRecipientType[0,0]"]);
	await kony.automation.playback.waitFor(["frmManageRecipientList","btnAddRecipient"]);
	kony.automation.button.click(["frmManageRecipientList","btnAddRecipient"]);
	await kony.automation.playback.waitFor(["frmEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFive"]);
	await kony.automation.playback.waitFor(["frmEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFive"]);
	await kony.automation.playback.waitFor(["frmEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFive"]);
	await kony.automation.playback.waitFor(["frmEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFive"]);
	await kony.automation.playback.waitFor(["frmEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmEnterBenAccNo","keypad","btnFive"]);
	await kony.automation.playback.waitFor(["frmEnterBenAccNo","btnContinue"]);
	kony.automation.button.click(["frmEnterBenAccNo","btnContinue"]);
	await kony.automation.playback.waitFor(["frmReEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFive"]);
	await kony.automation.playback.waitFor(["frmReEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFive"]);
	await kony.automation.playback.waitFor(["frmReEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFive"]);
	await kony.automation.playback.waitFor(["frmReEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFive"]);
	await kony.automation.playback.waitFor(["frmReEnterBenAccNo","keypad","btnFive"]);
	kony.automation.button.click(["frmReEnterBenAccNo","keypad","btnFive"]);
	await kony.automation.playback.waitFor(["frmReEnterBenAccNo","btnContinue"]);
	kony.automation.button.click(["frmReEnterBenAccNo","btnContinue"]);
	await kony.automation.playback.waitFor(["frmBenName","txtRecipientName"]);
	kony.automation.textbox.enterText(["frmBenName","txtRecipientName"],"externbank");
	await kony.automation.playback.waitFor(["frmBenName","btnContinue"]);
	kony.automation.button.click(["frmBenName","btnContinue"]);
	await kony.automation.playback.waitFor(["frmBenVerifyDetails","btnContinue"]);
	kony.automation.button.click(["frmBenVerifyDetails","btnContinue"]);
});