define(function() {
    return {
        "properties": [{
            "name": "sheetBackgroundSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerMainText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "option1Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "closeText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "option2Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerSubText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerBackgroundSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "option3Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerMainTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerButtonSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerButtonFocusSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerSubTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "option4Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "option5Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "separatorSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "option6Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "option7Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "option8Text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "optionsSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "optionsFocusSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["show", "dismiss"],
        "events": ["onClickOption1", "onClickOption2", "onClickOption3", "onClickOption4", "onClickOption5", "onClickOption6", "onClickOption7", "onClickOption8", "onClose"]
    }
});