define(function() {
    return {
        "properties": [{
            "name": "isSearchEnabled",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchTextBoxSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rowExpandIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchPlaceholderText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataGridContractLayerResponseRootPath",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataGridCustomerLayerResponseRootPath",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "button1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rowCollpaseIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "searchTextBoxIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataGridContractLayerLabel1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataGridCustomerLayerLabel1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "separatorSuffixLinkedCustomers",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "button1Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "checkboxSelectedIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataGridContractLayerLabel2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataGridCustomerLayerLabel2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblHeading",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "datagridHeadingLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getOperationCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "checkboxUnSelectedIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataGridContractLayerLabel3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "editobjectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "datagridContractRowSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataGridIcon1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "businessPayeeIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "getOperationIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "editobjectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "datagridCustomerRowSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataGridIcon2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "personalPayeeIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "editOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "datagridContractLayerLabel1skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "editOperationCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "datagridContractLayerLabel2skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "editOperationIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "datagridCustomerLayerLabel1skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "datagridCustomerLayerLabel2skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionButtonBlocked",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknActionButtonFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": ["setContext"]
    }
});