define(function() {
    return {
        "properties": [{
            "name": "keySkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fieldCount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "infoImage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tncCheckedImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tncText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successPopUp",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tncCheck",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "valueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Key",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "infoText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "object",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tncUncheckedImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tncButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "errPopUp",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionButtonActiveSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "activateOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Key",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "activateCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionButtonInactiveSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberMasking",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "activateIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "actionButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext", "setParentScope"],
        "events": ["onError"]
    }
});