define(function() {
    return {
        "properties": [{
            "name": "lblField1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknlblSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeObjectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ackPage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "minFillMapping",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField1Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknlblField",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "imgAcknowledgementError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dvfConfig",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField2Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknlblFieldValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeCREATEOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblAcknowledgementError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField3Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknBtnAction1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeCREATECriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "imgAcknowledgementSuccess",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField4Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknBtnActionFocus1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeCREATEIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblAcknowledgementSuccess",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField5Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField6",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknEditLblField",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeEDITOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReference",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField6Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblFieldValue1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTxtValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeEDITCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblReferenceValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField7Edit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblFieldValue2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknNonEditbaleContainer",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeEDITIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblFieldValue3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknBtnAction2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "customCREATEOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblFieldValue4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknBtnActionFocus2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "customCREATECriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblFieldValue5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknlblAcknowledgment",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "customCREATEIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblFieldValue6",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknlblReference",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btn1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknlblReferenceValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btn2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknBtnError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblEditField1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTextBoxError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtEditValue1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknTxtboxFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblEditField2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "txtEditValue2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblField7",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblFieldValue7",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext"],
        "events": []
    }
});