define(function() {
    return {
        "properties": [{
            "name": "objectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknHeaderLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successAcknowledgementTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "failureAcknowledgementTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successImage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "nicknameDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknHeaderBackground",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successAcknowledgementDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "failureAcknowledgementDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "failureImage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "nicknameTextboxValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "payeeStatus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknNicknameDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backbuttonIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successButtonAction1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "failureButtonAction1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "nicknameButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceResponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknNicknameDescriptionBackground",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successButtonAction2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknRowSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "criteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successButtonAction3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknNicknameTextbox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "successButtonAction4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSuccessAcknowledgementTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFailureAcknowledgementTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknSuccessAcknowledgementDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknFailureAcknowledgementDescription",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknEnabledButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknDisabledButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": ["requestStart", "requestEnd", "onError", "setContext", "getBtnEntitlement", "contextualActionButtonOnClick", "onBack", "iphonePayeeAcknowledgmentHeaderHandler"]
    }
});