define(function() {
    return {
        "properties": [{
            "name": "speechOnIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "speechOnIconScaleMode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "speechOffIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "speechOffIconScaleMode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "imageFlexSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "setAndroidLanguage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "preUtteranceDelay",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "setWebLanguage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "postUtteranceDelay",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "setPitch",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pitchMultiplier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "setWebVolume",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "setIphoneLanguage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "volume",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "setRate",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "stopSpeechApibehaviour",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["speakOut", "stopSpeech"],
        "events": ["speechOn", "speechOff"]
    }
});