/*
    This is an auto generated file and any modifications to it may result in corrupted data.
*/
define([], function() {
	var mappings = {
		"TransactionType": "TransactionType",
		"Status": "Status",
		"Request_id": "Request_id",
		"CompanyName": "CompanyName",
		"DebitOrCreditAccount": "DebitOrCreditAccount",
		"Amount": "Amount",
		"CreatedOn": "CreatedOn",
		"CreatedBy": "CreatedBy",
		"Company_id": "Company_id",
		"RequestCreatedby": "RequestCreatedby",
		"Payee": "Payee",
		"Date": "Date",
		"Transaction_id": "Transaction_id",
		"Frequency": "Frequency",
		"Reccurence": "Reccurence",
		"BBGeneralTransactionType_id": "BBGeneralTransactionType_id",
		"StatusId": "StatusId",
		"TemplateRequestTypeId": "TemplateRequestTypeId",
		"userName": "userName",
		"TemplateTypeId": "TemplateTypeId",
		"RequestType": "RequestType",
		"TemplateTypeValue": "TemplateTypeValue",
		"softDelete": "softDelete",
		"TransactionType_id": "TransactionType_id",
		"TemplateType": "TemplateType",
		"TransmittedDate": "TransmittedDate",
		"TransactionId": "TransactionId",
		"UpdatedDateAndTime": "UpdatedDateAndTime",
		"MaxAmount": "MaxAmount",
		"FileName": "FileName",
		"NumberOfDebits": "NumberOfDebits",
		"NumberOfPrenotes": "NumberOfPrenotes",
		"NumberOfCredits": "NumberOfCredits",
		"formatType": "formatType",
		"ACHFileFormatType_id": "ACHFileFormatType_id",
		"ACHFile_id": "ACHFile_id",
		"TotalCreditAmount": "TotalCreditAmount",
		"TotalDebitAmount": "TotalDebitAmount",
		"FileRequestType": "FileRequestType",
		"CreatedById": "CreatedById",
		"ActedBy": "ActedBy",
		"TransactionTypeValue": "TransactionTypeValue",
		"TotalAmount": "TotalAmount",
		"dbpErrMsg": "dbpErrMsg",
		"dbpErrCode": "dbpErrCode",
		"opstatus": "opstatus",
		"httpStatusCode": "httpStatusCode",
		"queryType": "queryType",
		"sortByParam": "sortByParam",
		"sortOrder": "sortOrder",
		"pageSize": "pageSize",
		"pageOffset": "pageOffset",
		"searchString": "searchString",
		"FeatureAction_id": "FeatureAction_id",
		"receivedApprovals": "receivedApprovals",
		"requiredApprovals": "requiredApprovals",
		"approvalId": "approvalId",
		"Actionts": "Actionts",
		"userFullName": "userFullName",
		"filterByParam": "filterByParam",
		"filterByValue": "filterByValue",
		"featureName": "featureName",
		"payeeName": "payeeName",
		"approvalAccounts": "approvalAccounts",
		"debitAccounts": "debitAccounts",
		"amICreator": "amICreator",
		"amIApprover": "amIApprover",
		"requestId": "requestId",
		"featureActionId": "featureActionId",
		"featureActionName": "featureActionName",
		"limitGroupId": "limitGroupId",
		"limitGroupName": "limitGroupName",
		"contractId": "contractId",
		"companyId": "companyId",
		"accountId": "accountId",
		"sentBy": "sentBy",
		"actedByMeAlready": "actedByMeAlready",
		"processingDate": "processingDate",
		"sentDate": "sentDate",
		"recurrence": "recurrence",
		"reference": "reference",
		"customerName": "customerName",
		"serviceCharge": "serviceCharge",
		"transactionAmount": "transactionAmount",
		"convertedAmount": "convertedAmount",
		"customerId": "customerId",
		"fileType": "fileType",
		"numberOfRecords": "numberOfRecords",
		"approvalDate": "approvalDate",
		"confirmationNumber": "confirmationNumber",
		"templateName": "templateName",
		"description": "description",
		"paymentId": "paymentId",
		"totalTransactions": "totalTransactions",
		"processingMode": "processingMode",
		"removeByParam": "removeByParam",
		"removeByValue": "removeByValue",
		"timeParam": "timeParam",
		"timeValue": "timeValue",
		"paidBy": "paidBy",
		"swiftCode": "swiftCode",
		"groupName": "groupName",
		"transactionCurrency": "transactionCurrency",
		"charges": "charges",
		"indicativeRate": "indicativeRate",
		"fromAccountCurrency": "fromAccountCurrency",
		"creditValueDate": "creditValueDate",
	};

	Object.freeze(mappings);

	var typings = {
		"TransactionType": "string",
		"Status": "string",
		"Request_id": "string",
		"CompanyName": "string",
		"DebitOrCreditAccount": "string",
		"Amount": "string",
		"CreatedOn": "string",
		"CreatedBy": "string",
		"Company_id": "string",
		"RequestCreatedby": "string",
		"Payee": "string",
		"Date": "string",
		"Transaction_id": "string",
		"Frequency": "string",
		"Reccurence": "string",
		"BBGeneralTransactionType_id": "string",
		"StatusId": "string",
		"TemplateRequestTypeId": "string",
		"userName": "string",
		"TemplateTypeId": "string",
		"RequestType": "string",
		"TemplateTypeValue": "string",
		"softDelete": "string",
		"TransactionType_id": "string",
		"TemplateType": "string",
		"TransmittedDate": "string",
		"TransactionId": "string",
		"UpdatedDateAndTime": "string",
		"MaxAmount": "string",
		"FileName": "string",
		"NumberOfDebits": "string",
		"NumberOfPrenotes": "string",
		"NumberOfCredits": "string",
		"formatType": "string",
		"ACHFileFormatType_id": "string",
		"ACHFile_id": "string",
		"TotalCreditAmount": "string",
		"TotalDebitAmount": "string",
		"FileRequestType": "string",
		"CreatedById": "string",
		"ActedBy": "string",
		"TransactionTypeValue": "string",
		"TotalAmount": "string",
		"dbpErrMsg": "string",
		"dbpErrCode": "string",
		"opstatus": "string",
		"httpStatusCode": "string",
		"queryType": "string",
		"sortByParam": "string",
		"sortOrder": "string",
		"pageSize": "string",
		"pageOffset": "string",
		"searchString": "string",
		"FeatureAction_id": "string",
		"receivedApprovals": "string",
		"requiredApprovals": "string",
		"approvalId": "string",
		"Actionts": "string",
		"userFullName": "string",
		"filterByParam": "string",
		"filterByValue": "string",
		"featureName": "string",
		"payeeName": "string",
		"approvalAccounts": "string",
		"debitAccounts": "string",
		"amICreator": "string",
		"amIApprover": "string",
		"requestId": "string",
		"featureActionId": "string",
		"featureActionName": "string",
		"limitGroupId": "string",
		"limitGroupName": "string",
		"contractId": "string",
		"companyId": "string",
		"accountId": "string",
		"sentBy": "string",
		"actedByMeAlready": "string",
		"processingDate": "string",
		"sentDate": "string",
		"recurrence": "string",
		"reference": "string",
		"customerName": "string",
		"serviceCharge": "string",
		"transactionAmount": "string",
		"convertedAmount": "string",
		"customerId": "string",
		"fileType": "string",
		"numberOfRecords": "string",
		"approvalDate": "string",
		"confirmationNumber": "string",
		"templateName": "string",
		"description": "string",
		"paymentId": "string",
		"totalTransactions": "string",
		"processingMode": "string",
		"removeByParam": "string",
		"removeByValue": "string",
		"timeParam": "string",
		"timeValue": "string",
		"paidBy": "string",
		"swiftCode": "string",
		"groupName": "string",
		"transactionCurrency": "string",
		"charges": "string",
		"indicativeRate": "string",
		"fromAccountCurrency": "string",
		"creditValueDate": "string",
	}

	Object.freeze(typings);

	var primaryKeys = [
					"Request_id",
	];

	Object.freeze(primaryKeys);

	var config = {
		mappings: mappings,
		typings: typings,
		primaryKeys: primaryKeys,
		serviceName: "ApprovalRequestObjects",
		tableName: "MyRequests"
	};

	Object.freeze(config);

	return config;
})