define(function() {
    return {
        "properties": [{
            "name": "serviceName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "button1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "labelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "alertText1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "retailIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "valueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "currencyCode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "combinedUserIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "button2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "criteria1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "statusLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "alertText2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountNumberFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "yesLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "button3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "statusImageFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "separatorSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accNoLengthDisplay",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "button4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceName2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "button5",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "criteria2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceName3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "criteria3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field5Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dataAvailability",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "serviceIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field6Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field7Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field8Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field9Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field10Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field11Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field11Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field11Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field12Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field12Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field12Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext"],
        "events": ["onSuccess", "onError", "onButtonAction", "showLoading", "dismissLoading"]
    }
});