define(function() {
    return {
        "properties": [{
            "name": "objectServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountTypeContextPath",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backgroundSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "amountFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "nickName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "labelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "objectName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "userTypeContextPath",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "backendDateFormat",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "highlightedLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "operationName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "currencyCodeContextPath",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field1Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noOfEllipsis",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "criteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noOfCharacters",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "highlightedValueSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "identifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "businessAccount",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "positiveAmountSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field2Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "negativeAmountSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dateSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field3Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "field4Type",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext", "getContext"],
        "events": ["onError", "requestStart", "requestEnd", "onFilterClickAction", "setSearchText", "onLoanScheduleClick", "onResetSearch"]
    }
});