define(function() {
    return {
        "properties": [{
            "name": "gsknHeaderLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ctsSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accValidationService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssSwiftLookupService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssResultItemFlexSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsSwiftLookupBtnSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "linkPayeeSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "easSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccsCountryListService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccssSearchboxFlx",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pynsSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoLookupSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accNumericInputBottomSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "iconBack",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "dvfConfig",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "nisSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "eassOROptionFlexSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcssSearchboxFlx",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ctsContactTypeSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "annSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ctsContactSelectionSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssResultItemFlexSelectSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccssSearchBoxSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknHeaderFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ctsValues",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accValidationObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssSwiftLookupObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsGetSwiftService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssValueEditableSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pynsSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "easSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccsCountryListOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnosFieldValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoSubheader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accInputFieldMaskedSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "minFillMapping",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "nisSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "eassOROptionLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcSearchbox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcssSearchBoxSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsOROptionFlexSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "annSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcEmailContactsData",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pynsVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssResultItemLabel1Skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccssResultItemFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknCancelBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accValidationOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssSwiftLookupOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsSwiftObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssValueReadonlySkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "easTextBoxInput",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccsCountryListObject",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoKeypadClearIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accInputFieldUnmaskedSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maxFillMapping",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "nisTextBoxInput",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnosOROptionFlexSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "eassPickEmailSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcssResultItemFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsOROptionLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "annTextbox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcPhoneNoContactsData",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pynsTextbox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssResultItemLabel2Skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccssResultItemFlexSelected",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accValidationCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssSearchResultsIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsSwiftOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssRowSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "easErrorMessage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccsCountryListCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoCCVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "jsonObjName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "nisErrorMessage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnosOROptionLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcssResultItemFlexSelected",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "annCTAButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accNumericInputBottomErrorSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pynsErrorMessage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoTxtbox1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssResultItemLabel3Skin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccssSegSortAlphabetSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "beneficiaryTypes",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "inputValuesPool",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsSwiftCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfssRowSeparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccsCListReponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "nisCTAButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnosPickPhoneNoSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "easOROption",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcssSegLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcsNoRecords",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "pynsCTAButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoTxtbox1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssEnableCache",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccssSegAlphabetBG",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknSubHeaderFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accScreen1SubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cancelButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsSwiftResponseIdentifier",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccsCountryListMasterData",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "easCTAButton1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcssSegAlphabetBG",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnosTbxValueSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "easCTAButton2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoTxtbox2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccssSegLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsAcceptBICSwift",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknSubHeaderLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accScreen2SubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccsCountryListSource",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcssSegSortAlphabetSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnosLabelValueSkn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoTxtbox2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssSubHeaderTitle1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsAcceptClearcode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknSubHeaderseparator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accTxtInput",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccsSectionHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cccsNoRecordsSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cfcssNoRecordsSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsHdr",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accReTxtInput",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "ccsSearchbox",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoOROption",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoCTABtn1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsSubhdr",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accCTAButton1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsObjectService",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "cccsNoRecords",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssTextbox1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsTextbox1Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accCTAButton2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsOperation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox5Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoCTABtn2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "phnoCTABtn3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox5Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssTextbox1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsTextbox1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accErrorMessage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssTextbox2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsSectionTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsTextbox2Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accReEnterErrorMessage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox6Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsTextBox6Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssTextbox2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsTextbox2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accExistMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsIconEdit",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssTextbox3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField1Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsTextbox3Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accInvalidMsg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsErrorMessage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "adsCTAButton",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssTextbox3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField1Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsTextbox3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accKeypadClearIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssTextbox4Label",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField2Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknPrimaryContexualBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBox1Visibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssTextbox4",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField2Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBox2Visibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssCTA1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsCTAButton1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField3Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknDisabledContexualBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBox3Visibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "resultScreenSubHeader",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsCTAButton2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField3Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBox4Visibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "resultItemLabel1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField4Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rcsOROption",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBox5Visibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "resultItemLabel2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField4Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBox6Visibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "resultItemLabel3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField5Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssSelectedTickImg",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField5Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknTextBoxNormal",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssCTA2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField6Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssCTA3",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField6Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknTextBoxFocus",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField7Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknTextBoxError",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssCriteria",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField7Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sbssResponseObj",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField8Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknErrorTextMessage",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField8Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField9Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField9Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField10Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField10Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField11Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknInputFieldLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField11Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField12Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField12Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField13Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknContentFlex",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gsknSecondaryContexualBtn",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField13Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField14Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField14Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField15Lbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField15Value",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsPayeeAddLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField1Address",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField2Address",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField3Address",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField4Address",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField5Address",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsField6Address",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsCTAButton1",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "vfsCTAButton2",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setContext", "goBack"],
        "events": ["onRequestStart", "onRequestEnd", "onBackButtonClick", "createAccountCallback", "iPhoneHeaderProps"]
    }
});