define(function() {
    return {
        "properties": [{
            "name": "identityServiceName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textBoxNormalSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textVisiblityOffIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tbx1PlaceholderText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rememberMeLabelSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textVisiblityOnIcon",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "tbx2PlaceholderText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "rememberMeSwitchSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblRememberMeText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnLoginSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "lblForgotPasswordText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "submitButtonText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnLoginDisabledSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": ["onFocusStart", "onFocusEnd", "hideDashboardIcon", "onLoginSuccess", "setErrorStatus", "forgotNavigation", "setUIAtFormLevelEvent", "initiateLoginFlow", "onLoginFailure"]
    }
});