define(function() {
    return {
        "properties": [{
            "name": "sknLink",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "accountType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknLinkValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "link1CTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknAddLink",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "link2CTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknAddLinkValue",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "link3CTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknAddLinkSeperator",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "link4CTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknContainer",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "link5CTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknBackground",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "link6CTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "sknCancelLink",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "link7CTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "link8CTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "link9CTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "link10CTA",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "isPrimaryVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "linkCancel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["setParentScopeAndEntitlements", "setContext", "showContextualActions", "setLinkVisibilityToContext"],
        "events": ["onError", "getActionEntitlement"]
    }
});